// Code generated by ent, DO NOT EDIT.

package executionlog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldTenantID, v))
}

// ScriptID applies equality check predicate on the "script_id" field. It's identical to ScriptIDEQ.
func ScriptID(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptID, v))
}

// ScriptName applies equality check predicate on the "script_name" field. It's identical to ScriptNameEQ.
func ScriptName(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptName, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldClientID, v))
}

// ScriptHash applies equality check predicate on the "script_hash" field. It's identical to ScriptHashEQ.
func ScriptHash(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptHash, v))
}

// ExitCode applies equality check predicate on the "exit_code" field. It's identical to ExitCodeEQ.
func ExitCode(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldExitCode, v))
}

// Output applies equality check predicate on the "output" field. It's identical to OutputEQ.
func Output(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldOutput, v))
}

// ErrorOutput applies equality check predicate on the "error_output" field. It's identical to ErrorOutputEQ.
func ErrorOutput(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldErrorOutput, v))
}

// RejectionReason applies equality check predicate on the "rejection_reason" field. It's identical to RejectionReasonEQ.
func RejectionReason(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldRejectionReason, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldStartedAt, v))
}

// CompletedAt applies equality check predicate on the "completed_at" field. It's identical to CompletedAtEQ.
func CompletedAt(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCompletedAt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldDurationMs, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldTenantID))
}

// ScriptIDEQ applies the EQ predicate on the "script_id" field.
func ScriptIDEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptID, v))
}

// ScriptIDNEQ applies the NEQ predicate on the "script_id" field.
func ScriptIDNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldScriptID, v))
}

// ScriptIDIn applies the In predicate on the "script_id" field.
func ScriptIDIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldScriptID, vs...))
}

// ScriptIDNotIn applies the NotIn predicate on the "script_id" field.
func ScriptIDNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldScriptID, vs...))
}

// ScriptIDGT applies the GT predicate on the "script_id" field.
func ScriptIDGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldScriptID, v))
}

// ScriptIDGTE applies the GTE predicate on the "script_id" field.
func ScriptIDGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldScriptID, v))
}

// ScriptIDLT applies the LT predicate on the "script_id" field.
func ScriptIDLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldScriptID, v))
}

// ScriptIDLTE applies the LTE predicate on the "script_id" field.
func ScriptIDLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldScriptID, v))
}

// ScriptIDContains applies the Contains predicate on the "script_id" field.
func ScriptIDContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldScriptID, v))
}

// ScriptIDHasPrefix applies the HasPrefix predicate on the "script_id" field.
func ScriptIDHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldScriptID, v))
}

// ScriptIDHasSuffix applies the HasSuffix predicate on the "script_id" field.
func ScriptIDHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldScriptID, v))
}

// ScriptIDEqualFold applies the EqualFold predicate on the "script_id" field.
func ScriptIDEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldScriptID, v))
}

// ScriptIDContainsFold applies the ContainsFold predicate on the "script_id" field.
func ScriptIDContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldScriptID, v))
}

// ScriptNameEQ applies the EQ predicate on the "script_name" field.
func ScriptNameEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptName, v))
}

// ScriptNameNEQ applies the NEQ predicate on the "script_name" field.
func ScriptNameNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldScriptName, v))
}

// ScriptNameIn applies the In predicate on the "script_name" field.
func ScriptNameIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldScriptName, vs...))
}

// ScriptNameNotIn applies the NotIn predicate on the "script_name" field.
func ScriptNameNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldScriptName, vs...))
}

// ScriptNameGT applies the GT predicate on the "script_name" field.
func ScriptNameGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldScriptName, v))
}

// ScriptNameGTE applies the GTE predicate on the "script_name" field.
func ScriptNameGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldScriptName, v))
}

// ScriptNameLT applies the LT predicate on the "script_name" field.
func ScriptNameLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldScriptName, v))
}

// ScriptNameLTE applies the LTE predicate on the "script_name" field.
func ScriptNameLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldScriptName, v))
}

// ScriptNameContains applies the Contains predicate on the "script_name" field.
func ScriptNameContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldScriptName, v))
}

// ScriptNameHasPrefix applies the HasPrefix predicate on the "script_name" field.
func ScriptNameHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldScriptName, v))
}

// ScriptNameHasSuffix applies the HasSuffix predicate on the "script_name" field.
func ScriptNameHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldScriptName, v))
}

// ScriptNameEqualFold applies the EqualFold predicate on the "script_name" field.
func ScriptNameEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldScriptName, v))
}

// ScriptNameContainsFold applies the ContainsFold predicate on the "script_name" field.
func ScriptNameContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldScriptName, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldClientID, v))
}

// ScriptHashEQ applies the EQ predicate on the "script_hash" field.
func ScriptHashEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldScriptHash, v))
}

// ScriptHashNEQ applies the NEQ predicate on the "script_hash" field.
func ScriptHashNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldScriptHash, v))
}

// ScriptHashIn applies the In predicate on the "script_hash" field.
func ScriptHashIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldScriptHash, vs...))
}

// ScriptHashNotIn applies the NotIn predicate on the "script_hash" field.
func ScriptHashNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldScriptHash, vs...))
}

// ScriptHashGT applies the GT predicate on the "script_hash" field.
func ScriptHashGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldScriptHash, v))
}

// ScriptHashGTE applies the GTE predicate on the "script_hash" field.
func ScriptHashGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldScriptHash, v))
}

// ScriptHashLT applies the LT predicate on the "script_hash" field.
func ScriptHashLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldScriptHash, v))
}

// ScriptHashLTE applies the LTE predicate on the "script_hash" field.
func ScriptHashLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldScriptHash, v))
}

// ScriptHashContains applies the Contains predicate on the "script_hash" field.
func ScriptHashContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldScriptHash, v))
}

// ScriptHashHasPrefix applies the HasPrefix predicate on the "script_hash" field.
func ScriptHashHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldScriptHash, v))
}

// ScriptHashHasSuffix applies the HasSuffix predicate on the "script_hash" field.
func ScriptHashHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldScriptHash, v))
}

// ScriptHashEqualFold applies the EqualFold predicate on the "script_hash" field.
func ScriptHashEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldScriptHash, v))
}

// ScriptHashContainsFold applies the ContainsFold predicate on the "script_hash" field.
func ScriptHashContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldScriptHash, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v TriggerType) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v TriggerType) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...TriggerType) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...TriggerType) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldTriggerType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldStatus, vs...))
}

// ExitCodeEQ applies the EQ predicate on the "exit_code" field.
func ExitCodeEQ(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldExitCode, v))
}

// ExitCodeNEQ applies the NEQ predicate on the "exit_code" field.
func ExitCodeNEQ(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldExitCode, v))
}

// ExitCodeIn applies the In predicate on the "exit_code" field.
func ExitCodeIn(vs ...int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldExitCode, vs...))
}

// ExitCodeNotIn applies the NotIn predicate on the "exit_code" field.
func ExitCodeNotIn(vs ...int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldExitCode, vs...))
}

// ExitCodeGT applies the GT predicate on the "exit_code" field.
func ExitCodeGT(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldExitCode, v))
}

// ExitCodeGTE applies the GTE predicate on the "exit_code" field.
func ExitCodeGTE(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldExitCode, v))
}

// ExitCodeLT applies the LT predicate on the "exit_code" field.
func ExitCodeLT(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldExitCode, v))
}

// ExitCodeLTE applies the LTE predicate on the "exit_code" field.
func ExitCodeLTE(v int) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldExitCode, v))
}

// ExitCodeIsNil applies the IsNil predicate on the "exit_code" field.
func ExitCodeIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldExitCode))
}

// ExitCodeNotNil applies the NotNil predicate on the "exit_code" field.
func ExitCodeNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldExitCode))
}

// OutputEQ applies the EQ predicate on the "output" field.
func OutputEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldOutput, v))
}

// OutputNEQ applies the NEQ predicate on the "output" field.
func OutputNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldOutput, v))
}

// OutputIn applies the In predicate on the "output" field.
func OutputIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldOutput, vs...))
}

// OutputNotIn applies the NotIn predicate on the "output" field.
func OutputNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldOutput, vs...))
}

// OutputGT applies the GT predicate on the "output" field.
func OutputGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldOutput, v))
}

// OutputGTE applies the GTE predicate on the "output" field.
func OutputGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldOutput, v))
}

// OutputLT applies the LT predicate on the "output" field.
func OutputLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldOutput, v))
}

// OutputLTE applies the LTE predicate on the "output" field.
func OutputLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldOutput, v))
}

// OutputContains applies the Contains predicate on the "output" field.
func OutputContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldOutput, v))
}

// OutputHasPrefix applies the HasPrefix predicate on the "output" field.
func OutputHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldOutput, v))
}

// OutputHasSuffix applies the HasSuffix predicate on the "output" field.
func OutputHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldOutput, v))
}

// OutputIsNil applies the IsNil predicate on the "output" field.
func OutputIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldOutput))
}

// OutputNotNil applies the NotNil predicate on the "output" field.
func OutputNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldOutput))
}

// OutputEqualFold applies the EqualFold predicate on the "output" field.
func OutputEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldOutput, v))
}

// OutputContainsFold applies the ContainsFold predicate on the "output" field.
func OutputContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldOutput, v))
}

// ErrorOutputEQ applies the EQ predicate on the "error_output" field.
func ErrorOutputEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldErrorOutput, v))
}

// ErrorOutputNEQ applies the NEQ predicate on the "error_output" field.
func ErrorOutputNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldErrorOutput, v))
}

// ErrorOutputIn applies the In predicate on the "error_output" field.
func ErrorOutputIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldErrorOutput, vs...))
}

// ErrorOutputNotIn applies the NotIn predicate on the "error_output" field.
func ErrorOutputNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldErrorOutput, vs...))
}

// ErrorOutputGT applies the GT predicate on the "error_output" field.
func ErrorOutputGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldErrorOutput, v))
}

// ErrorOutputGTE applies the GTE predicate on the "error_output" field.
func ErrorOutputGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldErrorOutput, v))
}

// ErrorOutputLT applies the LT predicate on the "error_output" field.
func ErrorOutputLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldErrorOutput, v))
}

// ErrorOutputLTE applies the LTE predicate on the "error_output" field.
func ErrorOutputLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldErrorOutput, v))
}

// ErrorOutputContains applies the Contains predicate on the "error_output" field.
func ErrorOutputContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldErrorOutput, v))
}

// ErrorOutputHasPrefix applies the HasPrefix predicate on the "error_output" field.
func ErrorOutputHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldErrorOutput, v))
}

// ErrorOutputHasSuffix applies the HasSuffix predicate on the "error_output" field.
func ErrorOutputHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldErrorOutput, v))
}

// ErrorOutputIsNil applies the IsNil predicate on the "error_output" field.
func ErrorOutputIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldErrorOutput))
}

// ErrorOutputNotNil applies the NotNil predicate on the "error_output" field.
func ErrorOutputNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldErrorOutput))
}

// ErrorOutputEqualFold applies the EqualFold predicate on the "error_output" field.
func ErrorOutputEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldErrorOutput, v))
}

// ErrorOutputContainsFold applies the ContainsFold predicate on the "error_output" field.
func ErrorOutputContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldErrorOutput, v))
}

// RejectionReasonEQ applies the EQ predicate on the "rejection_reason" field.
func RejectionReasonEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldRejectionReason, v))
}

// RejectionReasonNEQ applies the NEQ predicate on the "rejection_reason" field.
func RejectionReasonNEQ(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldRejectionReason, v))
}

// RejectionReasonIn applies the In predicate on the "rejection_reason" field.
func RejectionReasonIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldRejectionReason, vs...))
}

// RejectionReasonNotIn applies the NotIn predicate on the "rejection_reason" field.
func RejectionReasonNotIn(vs ...string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldRejectionReason, vs...))
}

// RejectionReasonGT applies the GT predicate on the "rejection_reason" field.
func RejectionReasonGT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldRejectionReason, v))
}

// RejectionReasonGTE applies the GTE predicate on the "rejection_reason" field.
func RejectionReasonGTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldRejectionReason, v))
}

// RejectionReasonLT applies the LT predicate on the "rejection_reason" field.
func RejectionReasonLT(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldRejectionReason, v))
}

// RejectionReasonLTE applies the LTE predicate on the "rejection_reason" field.
func RejectionReasonLTE(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldRejectionReason, v))
}

// RejectionReasonContains applies the Contains predicate on the "rejection_reason" field.
func RejectionReasonContains(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContains(FieldRejectionReason, v))
}

// RejectionReasonHasPrefix applies the HasPrefix predicate on the "rejection_reason" field.
func RejectionReasonHasPrefix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasPrefix(FieldRejectionReason, v))
}

// RejectionReasonHasSuffix applies the HasSuffix predicate on the "rejection_reason" field.
func RejectionReasonHasSuffix(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldHasSuffix(FieldRejectionReason, v))
}

// RejectionReasonIsNil applies the IsNil predicate on the "rejection_reason" field.
func RejectionReasonIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldRejectionReason))
}

// RejectionReasonNotNil applies the NotNil predicate on the "rejection_reason" field.
func RejectionReasonNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldRejectionReason))
}

// RejectionReasonEqualFold applies the EqualFold predicate on the "rejection_reason" field.
func RejectionReasonEqualFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEqualFold(FieldRejectionReason, v))
}

// RejectionReasonContainsFold applies the ContainsFold predicate on the "rejection_reason" field.
func RejectionReasonContainsFold(v string) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldContainsFold(FieldRejectionReason, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldStartedAt))
}

// CompletedAtEQ applies the EQ predicate on the "completed_at" field.
func CompletedAtEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldCompletedAt, v))
}

// CompletedAtNEQ applies the NEQ predicate on the "completed_at" field.
func CompletedAtNEQ(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldCompletedAt, v))
}

// CompletedAtIn applies the In predicate on the "completed_at" field.
func CompletedAtIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldCompletedAt, vs...))
}

// CompletedAtNotIn applies the NotIn predicate on the "completed_at" field.
func CompletedAtNotIn(vs ...time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldCompletedAt, vs...))
}

// CompletedAtGT applies the GT predicate on the "completed_at" field.
func CompletedAtGT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldCompletedAt, v))
}

// CompletedAtGTE applies the GTE predicate on the "completed_at" field.
func CompletedAtGTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldCompletedAt, v))
}

// CompletedAtLT applies the LT predicate on the "completed_at" field.
func CompletedAtLT(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldCompletedAt, v))
}

// CompletedAtLTE applies the LTE predicate on the "completed_at" field.
func CompletedAtLTE(v time.Time) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldCompletedAt, v))
}

// CompletedAtIsNil applies the IsNil predicate on the "completed_at" field.
func CompletedAtIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldCompletedAt))
}

// CompletedAtNotNil applies the NotNil predicate on the "completed_at" field.
func CompletedAtNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldCompletedAt))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldLTE(FieldDurationMs, v))
}

// DurationMsIsNil applies the IsNil predicate on the "duration_ms" field.
func DurationMsIsNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldIsNull(FieldDurationMs))
}

// DurationMsNotNil applies the NotNil predicate on the "duration_ms" field.
func DurationMsNotNil() predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.FieldNotNull(FieldDurationMs))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ExecutionLog) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ExecutionLog) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ExecutionLog) predicate.ExecutionLog {
	return predicate.ExecutionLog(sql.NotPredicates(p))
}
