// Code generated by ent, DO NOT EDIT.

package scriptassignment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldContainsFold(FieldID, id))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldCreateBy, v))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldCreateTime, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldUpdateTime, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldDeleteTime, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldTenantID, v))
}

// ScriptID applies equality check predicate on the "script_id" field. It's identical to ScriptIDEQ.
func ScriptID(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldScriptID, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldClientID, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotNull(FieldCreateBy))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldCreateTime, v))
}

// CreateTimeIsNil applies the IsNil predicate on the "create_time" field.
func CreateTimeIsNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIsNull(FieldCreateTime))
}

// CreateTimeNotNil applies the NotNil predicate on the "create_time" field.
func CreateTimeNotNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotNull(FieldCreateTime))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateTimeIsNil applies the IsNil predicate on the "update_time" field.
func UpdateTimeIsNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIsNull(FieldUpdateTime))
}

// UpdateTimeNotNil applies the NotNil predicate on the "update_time" field.
func UpdateTimeNotNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotNull(FieldUpdateTime))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotNull(FieldDeleteTime))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotNull(FieldTenantID))
}

// ScriptIDEQ applies the EQ predicate on the "script_id" field.
func ScriptIDEQ(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldScriptID, v))
}

// ScriptIDNEQ applies the NEQ predicate on the "script_id" field.
func ScriptIDNEQ(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldScriptID, v))
}

// ScriptIDIn applies the In predicate on the "script_id" field.
func ScriptIDIn(vs ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldScriptID, vs...))
}

// ScriptIDNotIn applies the NotIn predicate on the "script_id" field.
func ScriptIDNotIn(vs ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldScriptID, vs...))
}

// ScriptIDGT applies the GT predicate on the "script_id" field.
func ScriptIDGT(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldScriptID, v))
}

// ScriptIDGTE applies the GTE predicate on the "script_id" field.
func ScriptIDGTE(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldScriptID, v))
}

// ScriptIDLT applies the LT predicate on the "script_id" field.
func ScriptIDLT(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldScriptID, v))
}

// ScriptIDLTE applies the LTE predicate on the "script_id" field.
func ScriptIDLTE(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldScriptID, v))
}

// ScriptIDContains applies the Contains predicate on the "script_id" field.
func ScriptIDContains(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldContains(FieldScriptID, v))
}

// ScriptIDHasPrefix applies the HasPrefix predicate on the "script_id" field.
func ScriptIDHasPrefix(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldHasPrefix(FieldScriptID, v))
}

// ScriptIDHasSuffix applies the HasSuffix predicate on the "script_id" field.
func ScriptIDHasSuffix(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldHasSuffix(FieldScriptID, v))
}

// ScriptIDEqualFold applies the EqualFold predicate on the "script_id" field.
func ScriptIDEqualFold(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEqualFold(FieldScriptID, v))
}

// ScriptIDContainsFold applies the ContainsFold predicate on the "script_id" field.
func ScriptIDContainsFold(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldContainsFold(FieldScriptID, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldLTE(FieldClientID, v))
}

// ClientIDContains applies the Contains predicate on the "client_id" field.
func ClientIDContains(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldContains(FieldClientID, v))
}

// ClientIDHasPrefix applies the HasPrefix predicate on the "client_id" field.
func ClientIDHasPrefix(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldHasPrefix(FieldClientID, v))
}

// ClientIDHasSuffix applies the HasSuffix predicate on the "client_id" field.
func ClientIDHasSuffix(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldHasSuffix(FieldClientID, v))
}

// ClientIDEqualFold applies the EqualFold predicate on the "client_id" field.
func ClientIDEqualFold(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldEqualFold(FieldClientID, v))
}

// ClientIDContainsFold applies the ContainsFold predicate on the "client_id" field.
func ClientIDContainsFold(v string) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.FieldContainsFold(FieldClientID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ScriptAssignment) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ScriptAssignment) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ScriptAssignment) predicate.ScriptAssignment {
	return predicate.ScriptAssignment(sql.NotPredicates(p))
}
