// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"

	"github.com/go-tangra/go-tangra-executor/internal/data/ent/auditlog"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/executionlog"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/script"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/scriptassignment"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	auditlogMixin := schema.AuditLog{}.Mixin()
	auditlog.Policy = privacy.NewPolicies(auditlogMixin[2], schema.AuditLog{})
	auditlog.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := auditlog.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	auditlogMixinFields0 := auditlogMixin[0].Fields()
	_ = auditlogMixinFields0
	auditlogMixinFields2 := auditlogMixin[2].Fields()
	_ = auditlogMixinFields2
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescTenantID is the schema descriptor for tenant_id field.
	auditlogDescTenantID := auditlogMixinFields2[0].Descriptor()
	// auditlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	auditlog.DefaultTenantID = auditlogDescTenantID.Default.(uint32)
	// auditlogDescAuditID is the schema descriptor for audit_id field.
	auditlogDescAuditID := auditlogFields[0].Descriptor()
	// auditlog.AuditIDValidator is a validator for the "audit_id" field. It is called by the builders before save.
	auditlog.AuditIDValidator = auditlogDescAuditID.Validators[0].(func(string) error)
	// auditlogDescOperation is the schema descriptor for operation field.
	auditlogDescOperation := auditlogFields[2].Descriptor()
	// auditlog.OperationValidator is a validator for the "operation" field. It is called by the builders before save.
	auditlog.OperationValidator = auditlogDescOperation.Validators[0].(func(string) error)
	// auditlogDescServiceName is the schema descriptor for service_name field.
	auditlogDescServiceName := auditlogFields[3].Descriptor()
	// auditlog.DefaultServiceName holds the default value on creation for the service_name field.
	auditlog.DefaultServiceName = auditlogDescServiceName.Default.(string)
	// auditlogDescIsAuthenticated is the schema descriptor for is_authenticated field.
	auditlogDescIsAuthenticated := auditlogFields[8].Descriptor()
	// auditlog.DefaultIsAuthenticated holds the default value on creation for the is_authenticated field.
	auditlog.DefaultIsAuthenticated = auditlogDescIsAuthenticated.Default.(bool)
	// auditlogDescSuccess is the schema descriptor for success field.
	auditlogDescSuccess := auditlogFields[9].Descriptor()
	// auditlog.DefaultSuccess holds the default value on creation for the success field.
	auditlog.DefaultSuccess = auditlogDescSuccess.Default.(bool)
	// auditlogDescLatencyMs is the schema descriptor for latency_ms field.
	auditlogDescLatencyMs := auditlogFields[12].Descriptor()
	// auditlog.DefaultLatencyMs holds the default value on creation for the latency_ms field.
	auditlog.DefaultLatencyMs = auditlogDescLatencyMs.Default.(int64)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogMixinFields0[0].Descriptor()
	// auditlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	auditlog.IDValidator = auditlogDescID.Validators[0].(func(uint32) error)
	executionlogMixin := schema.ExecutionLog{}.Mixin()
	executionlog.Policy = privacy.NewPolicies(executionlogMixin[2], schema.ExecutionLog{})
	executionlog.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := executionlog.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	executionlogMixinFields2 := executionlogMixin[2].Fields()
	_ = executionlogMixinFields2
	executionlogFields := schema.ExecutionLog{}.Fields()
	_ = executionlogFields
	// executionlogDescTenantID is the schema descriptor for tenant_id field.
	executionlogDescTenantID := executionlogMixinFields2[0].Descriptor()
	// executionlog.DefaultTenantID holds the default value on creation for the tenant_id field.
	executionlog.DefaultTenantID = executionlogDescTenantID.Default.(uint32)
	// executionlogDescScriptID is the schema descriptor for script_id field.
	executionlogDescScriptID := executionlogFields[1].Descriptor()
	// executionlog.ScriptIDValidator is a validator for the "script_id" field. It is called by the builders before save.
	executionlog.ScriptIDValidator = func() func(string) error {
		validators := executionlogDescScriptID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(script_id string) error {
			for _, fn := range fns {
				if err := fn(script_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// executionlogDescScriptName is the schema descriptor for script_name field.
	executionlogDescScriptName := executionlogFields[2].Descriptor()
	// executionlog.ScriptNameValidator is a validator for the "script_name" field. It is called by the builders before save.
	executionlog.ScriptNameValidator = func() func(string) error {
		validators := executionlogDescScriptName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(script_name string) error {
			for _, fn := range fns {
				if err := fn(script_name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// executionlogDescClientID is the schema descriptor for client_id field.
	executionlogDescClientID := executionlogFields[3].Descriptor()
	// executionlog.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	executionlog.ClientIDValidator = func() func(string) error {
		validators := executionlogDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// executionlogDescScriptHash is the schema descriptor for script_hash field.
	executionlogDescScriptHash := executionlogFields[4].Descriptor()
	// executionlog.ScriptHashValidator is a validator for the "script_hash" field. It is called by the builders before save.
	executionlog.ScriptHashValidator = func() func(string) error {
		validators := executionlogDescScriptHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(script_hash string) error {
			for _, fn := range fns {
				if err := fn(script_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// executionlogDescRejectionReason is the schema descriptor for rejection_reason field.
	executionlogDescRejectionReason := executionlogFields[10].Descriptor()
	// executionlog.RejectionReasonValidator is a validator for the "rejection_reason" field. It is called by the builders before save.
	executionlog.RejectionReasonValidator = executionlogDescRejectionReason.Validators[0].(func(string) error)
	// executionlogDescID is the schema descriptor for id field.
	executionlogDescID := executionlogFields[0].Descriptor()
	// executionlog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	executionlog.IDValidator = executionlogDescID.Validators[0].(func(string) error)
	scriptMixin := schema.Script{}.Mixin()
	script.Policy = privacy.NewPolicies(scriptMixin[3], schema.Script{})
	script.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := script.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	scriptMixinFields3 := scriptMixin[3].Fields()
	_ = scriptMixinFields3
	scriptFields := schema.Script{}.Fields()
	_ = scriptFields
	// scriptDescTenantID is the schema descriptor for tenant_id field.
	scriptDescTenantID := scriptMixinFields3[0].Descriptor()
	// script.DefaultTenantID holds the default value on creation for the tenant_id field.
	script.DefaultTenantID = scriptDescTenantID.Default.(uint32)
	// scriptDescName is the schema descriptor for name field.
	scriptDescName := scriptFields[1].Descriptor()
	// script.NameValidator is a validator for the "name" field. It is called by the builders before save.
	script.NameValidator = func() func(string) error {
		validators := scriptDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scriptDescDescription is the schema descriptor for description field.
	scriptDescDescription := scriptFields[2].Descriptor()
	// script.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	script.DescriptionValidator = scriptDescDescription.Validators[0].(func(string) error)
	// scriptDescContentHash is the schema descriptor for content_hash field.
	scriptDescContentHash := scriptFields[5].Descriptor()
	// script.ContentHashValidator is a validator for the "content_hash" field. It is called by the builders before save.
	script.ContentHashValidator = func() func(string) error {
		validators := scriptDescContentHash.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content_hash string) error {
			for _, fn := range fns {
				if err := fn(content_hash); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scriptDescVersion is the schema descriptor for version field.
	scriptDescVersion := scriptFields[6].Descriptor()
	// script.DefaultVersion holds the default value on creation for the version field.
	script.DefaultVersion = scriptDescVersion.Default.(int)
	// scriptDescEnabled is the schema descriptor for enabled field.
	scriptDescEnabled := scriptFields[7].Descriptor()
	// script.DefaultEnabled holds the default value on creation for the enabled field.
	script.DefaultEnabled = scriptDescEnabled.Default.(bool)
	// scriptDescID is the schema descriptor for id field.
	scriptDescID := scriptFields[0].Descriptor()
	// script.IDValidator is a validator for the "id" field. It is called by the builders before save.
	script.IDValidator = scriptDescID.Validators[0].(func(string) error)
	scriptassignmentMixin := schema.ScriptAssignment{}.Mixin()
	scriptassignment.Policy = privacy.NewPolicies(scriptassignmentMixin[2], schema.ScriptAssignment{})
	scriptassignment.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := scriptassignment.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	scriptassignmentMixinFields2 := scriptassignmentMixin[2].Fields()
	_ = scriptassignmentMixinFields2
	scriptassignmentFields := schema.ScriptAssignment{}.Fields()
	_ = scriptassignmentFields
	// scriptassignmentDescTenantID is the schema descriptor for tenant_id field.
	scriptassignmentDescTenantID := scriptassignmentMixinFields2[0].Descriptor()
	// scriptassignment.DefaultTenantID holds the default value on creation for the tenant_id field.
	scriptassignment.DefaultTenantID = scriptassignmentDescTenantID.Default.(uint32)
	// scriptassignmentDescScriptID is the schema descriptor for script_id field.
	scriptassignmentDescScriptID := scriptassignmentFields[1].Descriptor()
	// scriptassignment.ScriptIDValidator is a validator for the "script_id" field. It is called by the builders before save.
	scriptassignment.ScriptIDValidator = func() func(string) error {
		validators := scriptassignmentDescScriptID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(script_id string) error {
			for _, fn := range fns {
				if err := fn(script_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scriptassignmentDescClientID is the schema descriptor for client_id field.
	scriptassignmentDescClientID := scriptassignmentFields[2].Descriptor()
	// scriptassignment.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	scriptassignment.ClientIDValidator = func() func(string) error {
		validators := scriptassignmentDescClientID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(client_id string) error {
			for _, fn := range fns {
				if err := fn(client_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// scriptassignmentDescID is the schema descriptor for id field.
	scriptassignmentDescID := scriptassignmentFields[0].Descriptor()
	// scriptassignment.IDValidator is a validator for the "id" field. It is called by the builders before save.
	scriptassignment.IDValidator = scriptassignmentDescID.Validators[0].(func(string) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
