// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/action"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/actionfile"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
)

// ActionUpdate is the builder for updating Action entities.
type ActionUpdate struct {
	config
	hooks     []Hook
	mutation  *ActionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ActionUpdate builder.
func (_u *ActionUpdate) Where(ps ...predicate.Action) *ActionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ActionUpdate) SetCreateBy(v uint32) *ActionUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableCreateBy(v *uint32) *ActionUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ActionUpdate) AddCreateBy(v int32) *ActionUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ActionUpdate) ClearCreateBy() *ActionUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ActionUpdate) SetUpdateBy(v uint32) *ActionUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableUpdateBy(v *uint32) *ActionUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ActionUpdate) AddUpdateBy(v int32) *ActionUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ActionUpdate) ClearUpdateBy() *ActionUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionUpdate) SetUpdateTime(v time.Time) *ActionUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableUpdateTime(v *time.Time) *ActionUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ActionUpdate) ClearUpdateTime() *ActionUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ActionUpdate) SetDeleteTime(v time.Time) *ActionUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableDeleteTime(v *time.Time) *ActionUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ActionUpdate) ClearDeleteTime() *ActionUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ActionUpdate) SetName(v string) *ActionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableName(v *string) *ActionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ActionUpdate) SetVersion(v int) *ActionUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableVersion(v *int) *ActionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ActionUpdate) AddVersion(v int) *ActionUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionUpdate) SetDescription(v string) *ActionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableDescription(v *string) *ActionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ActionUpdate) ClearDescription() *ActionUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetUsing sets the "using" field.
func (_u *ActionUpdate) SetUsing(v string) *ActionUpdate {
	_u.mutation.SetUsing(v)
	return _u
}

// SetNillableUsing sets the "using" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableUsing(v *string) *ActionUpdate {
	if v != nil {
		_u.SetUsing(*v)
	}
	return _u
}

// ClearUsing clears the value of the "using" field.
func (_u *ActionUpdate) ClearUsing() *ActionUpdate {
	_u.mutation.ClearUsing()
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *ActionUpdate) SetManifest(v string) *ActionUpdate {
	_u.mutation.SetManifest(v)
	return _u
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableManifest(v *string) *ActionUpdate {
	if v != nil {
		_u.SetManifest(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *ActionUpdate) SetContentHash(v string) *ActionUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableContentHash(v *string) *ActionUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ActionUpdate) SetEnabled(v bool) *ActionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ActionUpdate) SetNillableEnabled(v *bool) *ActionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the ActionFile entity by IDs.
func (_u *ActionUpdate) AddFileIDs(ids ...string) *ActionUpdate {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the ActionFile entity.
func (_u *ActionUpdate) AddFiles(v ...*ActionFile) *ActionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the ActionMutation object of the builder.
func (_u *ActionUpdate) Mutation() *ActionMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the ActionFile entity.
func (_u *ActionUpdate) ClearFiles() *ActionUpdate {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to ActionFile entities by IDs.
func (_u *ActionUpdate) RemoveFileIDs(ids ...string) *ActionUpdate {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to ActionFile entities.
func (_u *ActionUpdate) RemoveFiles(v ...*ActionFile) *ActionUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := action.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Action.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := action.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Action.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Using(); ok {
		if err := action.UsingValidator(v); err != nil {
			return &ValidationError{Name: "using", err: fmt.Errorf(`ent: validator failed for field "Action.using": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := action.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Action.content_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(action.Table, action.Columns, sqlgraph.NewFieldSpec(action.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(action.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(action.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(action.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(action.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(action.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(action.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(action.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(action.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(action.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(action.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(action.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(action.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(action.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(action.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(action.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(action.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(action.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Using(); ok {
		_spec.SetField(action.FieldUsing, field.TypeString, value)
	}
	if _u.mutation.UsingCleared() {
		_spec.ClearField(action.FieldUsing, field.TypeString)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(action.FieldManifest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(action.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(action.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{action.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionUpdateOne is the builder for updating a single Action entity.
type ActionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ActionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ActionUpdateOne) SetCreateBy(v uint32) *ActionUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableCreateBy(v *uint32) *ActionUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ActionUpdateOne) AddCreateBy(v int32) *ActionUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ActionUpdateOne) ClearCreateBy() *ActionUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ActionUpdateOne) SetUpdateBy(v uint32) *ActionUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableUpdateBy(v *uint32) *ActionUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ActionUpdateOne) AddUpdateBy(v int32) *ActionUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ActionUpdateOne) ClearUpdateBy() *ActionUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionUpdateOne) SetUpdateTime(v time.Time) *ActionUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableUpdateTime(v *time.Time) *ActionUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ActionUpdateOne) ClearUpdateTime() *ActionUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ActionUpdateOne) SetDeleteTime(v time.Time) *ActionUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableDeleteTime(v *time.Time) *ActionUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ActionUpdateOne) ClearDeleteTime() *ActionUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ActionUpdateOne) SetName(v string) *ActionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableName(v *string) *ActionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ActionUpdateOne) SetVersion(v int) *ActionUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableVersion(v *int) *ActionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ActionUpdateOne) AddVersion(v int) *ActionUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetDescription sets the "description" field.
func (_u *ActionUpdateOne) SetDescription(v string) *ActionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableDescription(v *string) *ActionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ActionUpdateOne) ClearDescription() *ActionUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetUsing sets the "using" field.
func (_u *ActionUpdateOne) SetUsing(v string) *ActionUpdateOne {
	_u.mutation.SetUsing(v)
	return _u
}

// SetNillableUsing sets the "using" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableUsing(v *string) *ActionUpdateOne {
	if v != nil {
		_u.SetUsing(*v)
	}
	return _u
}

// ClearUsing clears the value of the "using" field.
func (_u *ActionUpdateOne) ClearUsing() *ActionUpdateOne {
	_u.mutation.ClearUsing()
	return _u
}

// SetManifest sets the "manifest" field.
func (_u *ActionUpdateOne) SetManifest(v string) *ActionUpdateOne {
	_u.mutation.SetManifest(v)
	return _u
}

// SetNillableManifest sets the "manifest" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableManifest(v *string) *ActionUpdateOne {
	if v != nil {
		_u.SetManifest(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *ActionUpdateOne) SetContentHash(v string) *ActionUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableContentHash(v *string) *ActionUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ActionUpdateOne) SetEnabled(v bool) *ActionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ActionUpdateOne) SetNillableEnabled(v *bool) *ActionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// AddFileIDs adds the "files" edge to the ActionFile entity by IDs.
func (_u *ActionUpdateOne) AddFileIDs(ids ...string) *ActionUpdateOne {
	_u.mutation.AddFileIDs(ids...)
	return _u
}

// AddFiles adds the "files" edges to the ActionFile entity.
func (_u *ActionUpdateOne) AddFiles(v ...*ActionFile) *ActionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddFileIDs(ids...)
}

// Mutation returns the ActionMutation object of the builder.
func (_u *ActionUpdateOne) Mutation() *ActionMutation {
	return _u.mutation
}

// ClearFiles clears all "files" edges to the ActionFile entity.
func (_u *ActionUpdateOne) ClearFiles() *ActionUpdateOne {
	_u.mutation.ClearFiles()
	return _u
}

// RemoveFileIDs removes the "files" edge to ActionFile entities by IDs.
func (_u *ActionUpdateOne) RemoveFileIDs(ids ...string) *ActionUpdateOne {
	_u.mutation.RemoveFileIDs(ids...)
	return _u
}

// RemoveFiles removes "files" edges to ActionFile entities.
func (_u *ActionUpdateOne) RemoveFiles(v ...*ActionFile) *ActionUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveFileIDs(ids...)
}

// Where appends a list predicates to the ActionUpdate builder.
func (_u *ActionUpdateOne) Where(ps ...predicate.Action) *ActionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionUpdateOne) Select(field string, fields ...string) *ActionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Action entity.
func (_u *ActionUpdateOne) Save(ctx context.Context) (*Action, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionUpdateOne) SaveX(ctx context.Context) *Action {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := action.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Action.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := action.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Action.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Using(); ok {
		if err := action.UsingValidator(v); err != nil {
			return &ValidationError{Name: "using", err: fmt.Errorf(`ent: validator failed for field "Action.using": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := action.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Action.content_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionUpdateOne) sqlSave(ctx context.Context) (_node *Action, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(action.Table, action.Columns, sqlgraph.NewFieldSpec(action.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Action.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, action.FieldID)
		for _, f := range fields {
			if !action.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != action.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(action.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(action.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(action.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(action.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(action.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(action.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(action.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(action.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(action.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(action.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(action.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(action.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(action.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(action.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(action.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(action.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(action.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Using(); ok {
		_spec.SetField(action.FieldUsing, field.TypeString, value)
	}
	if _u.mutation.UsingCleared() {
		_spec.ClearField(action.FieldUsing, field.TypeString)
	}
	if value, ok := _u.mutation.Manifest(); ok {
		_spec.SetField(action.FieldManifest, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(action.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(action.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedFilesIDs(); len(nodes) > 0 && !_u.mutation.FilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   action.FilesTable,
			Columns: []string{action.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Action{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{action.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
