// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/action"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/actionfile"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
)

// ActionFileUpdate is the builder for updating ActionFile entities.
type ActionFileUpdate struct {
	config
	hooks     []Hook
	mutation  *ActionFileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ActionFileUpdate builder.
func (_u *ActionFileUpdate) Where(ps ...predicate.ActionFile) *ActionFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionFileUpdate) SetUpdateTime(v time.Time) *ActionFileUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ActionFileUpdate) SetNillableUpdateTime(v *time.Time) *ActionFileUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ActionFileUpdate) ClearUpdateTime() *ActionFileUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ActionFileUpdate) SetDeleteTime(v time.Time) *ActionFileUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ActionFileUpdate) SetNillableDeleteTime(v *time.Time) *ActionFileUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ActionFileUpdate) ClearDeleteTime() *ActionFileUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *ActionFileUpdate) SetActionID(v string) *ActionFileUpdate {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *ActionFileUpdate) SetNillableActionID(v *string) *ActionFileUpdate {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ActionFileUpdate) SetPath(v string) *ActionFileUpdate {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ActionFileUpdate) SetNillablePath(v *string) *ActionFileUpdate {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ActionFileUpdate) SetContent(v string) *ActionFileUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ActionFileUpdate) SetNillableContent(v *string) *ActionFileUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAction sets the "action" edge to the Action entity.
func (_u *ActionFileUpdate) SetAction(v *Action) *ActionFileUpdate {
	return _u.SetActionID(v.ID)
}

// Mutation returns the ActionFileMutation object of the builder.
func (_u *ActionFileUpdate) Mutation() *ActionFileMutation {
	return _u.mutation
}

// ClearAction clears the "action" edge to the Action entity.
func (_u *ActionFileUpdate) ClearAction() *ActionFileUpdate {
	_u.mutation.ClearAction()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ActionFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ActionFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionFileUpdate) check() error {
	if v, ok := _u.mutation.ActionID(); ok {
		if err := actionfile.ActionIDValidator(v); err != nil {
			return &ValidationError{Name: "action_id", err: fmt.Errorf(`ent: validator failed for field "ActionFile.action_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := actionfile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ActionFile.path": %w`, err)}
		}
	}
	if _u.mutation.ActionCleared() && len(_u.mutation.ActionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionFile.action"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionFileUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionFileUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actionfile.Table, actionfile.Columns, sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(actionfile.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(actionfile.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(actionfile.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(actionfile.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(actionfile.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(actionfile.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(actionfile.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionfile.ActionTable,
			Columns: []string{actionfile.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(action.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionfile.ActionTable,
			Columns: []string{actionfile.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(action.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ActionFileUpdateOne is the builder for updating a single ActionFile entity.
type ActionFileUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ActionFileMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdateTime sets the "update_time" field.
func (_u *ActionFileUpdateOne) SetUpdateTime(v time.Time) *ActionFileUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ActionFileUpdateOne) SetNillableUpdateTime(v *time.Time) *ActionFileUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ActionFileUpdateOne) ClearUpdateTime() *ActionFileUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ActionFileUpdateOne) SetDeleteTime(v time.Time) *ActionFileUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ActionFileUpdateOne) SetNillableDeleteTime(v *time.Time) *ActionFileUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ActionFileUpdateOne) ClearDeleteTime() *ActionFileUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetActionID sets the "action_id" field.
func (_u *ActionFileUpdateOne) SetActionID(v string) *ActionFileUpdateOne {
	_u.mutation.SetActionID(v)
	return _u
}

// SetNillableActionID sets the "action_id" field if the given value is not nil.
func (_u *ActionFileUpdateOne) SetNillableActionID(v *string) *ActionFileUpdateOne {
	if v != nil {
		_u.SetActionID(*v)
	}
	return _u
}

// SetPath sets the "path" field.
func (_u *ActionFileUpdateOne) SetPath(v string) *ActionFileUpdateOne {
	_u.mutation.SetPath(v)
	return _u
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_u *ActionFileUpdateOne) SetNillablePath(v *string) *ActionFileUpdateOne {
	if v != nil {
		_u.SetPath(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ActionFileUpdateOne) SetContent(v string) *ActionFileUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ActionFileUpdateOne) SetNillableContent(v *string) *ActionFileUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAction sets the "action" edge to the Action entity.
func (_u *ActionFileUpdateOne) SetAction(v *Action) *ActionFileUpdateOne {
	return _u.SetActionID(v.ID)
}

// Mutation returns the ActionFileMutation object of the builder.
func (_u *ActionFileUpdateOne) Mutation() *ActionFileMutation {
	return _u.mutation
}

// ClearAction clears the "action" edge to the Action entity.
func (_u *ActionFileUpdateOne) ClearAction() *ActionFileUpdateOne {
	_u.mutation.ClearAction()
	return _u
}

// Where appends a list predicates to the ActionFileUpdate builder.
func (_u *ActionFileUpdateOne) Where(ps ...predicate.ActionFile) *ActionFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ActionFileUpdateOne) Select(field string, fields ...string) *ActionFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ActionFile entity.
func (_u *ActionFileUpdateOne) Save(ctx context.Context) (*ActionFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ActionFileUpdateOne) SaveX(ctx context.Context) *ActionFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ActionFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ActionFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ActionFileUpdateOne) check() error {
	if v, ok := _u.mutation.ActionID(); ok {
		if err := actionfile.ActionIDValidator(v); err != nil {
			return &ValidationError{Name: "action_id", err: fmt.Errorf(`ent: validator failed for field "ActionFile.action_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Path(); ok {
		if err := actionfile.PathValidator(v); err != nil {
			return &ValidationError{Name: "path", err: fmt.Errorf(`ent: validator failed for field "ActionFile.path": %w`, err)}
		}
	}
	if _u.mutation.ActionCleared() && len(_u.mutation.ActionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ActionFile.action"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ActionFileUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ActionFileUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ActionFileUpdateOne) sqlSave(ctx context.Context) (_node *ActionFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(actionfile.Table, actionfile.Columns, sqlgraph.NewFieldSpec(actionfile.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ActionFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, actionfile.FieldID)
		for _, f := range fields {
			if !actionfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != actionfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(actionfile.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(actionfile.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(actionfile.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(actionfile.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(actionfile.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.Path(); ok {
		_spec.SetField(actionfile.FieldPath, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(actionfile.FieldContent, field.TypeString, value)
	}
	if _u.mutation.ActionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionfile.ActionTable,
			Columns: []string{actionfile.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(action.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   actionfile.ActionTable,
			Columns: []string{actionfile.ActionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(action.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ActionFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{actionfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
