// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/executionlog"
)

// ExecutionLog is the model entity for the ExecutionLog schema.
type ExecutionLog struct {
	config `json:"-"`
	// ID of the ent.
	// UUID primary key
	ID string `json:"id,omitempty"`
	// 创建者ID
	CreateBy *uint32 `json:"create_by,omitempty"`
	// 创建时间
	CreateTime *time.Time `json:"create_time,omitempty"`
	// 更新时间
	UpdateTime *time.Time `json:"update_time,omitempty"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// FK to executor_scripts
	ScriptID string `json:"script_id,omitempty"`
	// Denormalized script name for audit readability
	ScriptName string `json:"script_name,omitempty"`
	// mTLS client CN
	ClientID string `json:"client_id,omitempty"`
	// Script content hash at execution time
	ScriptHash string `json:"script_hash,omitempty"`
	// Who initiated the execution
	TriggerType executionlog.TriggerType `json:"trigger_type,omitempty"`
	// Current execution status
	Status executionlog.Status `json:"status,omitempty"`
	// Process exit code
	ExitCode *int `json:"exit_code,omitempty"`
	// Script stdout
	Output string `json:"output,omitempty"`
	// Script stderr
	ErrorOutput string `json:"error_output,omitempty"`
	// Why the client rejected execution
	RejectionReason string `json:"rejection_reason,omitempty"`
	// When execution started on client
	StartedAt *time.Time `json:"started_at,omitempty"`
	// When execution completed on client
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Execution duration in milliseconds
	DurationMs   *int64 `json:"duration_ms,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ExecutionLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case executionlog.FieldCreateBy, executionlog.FieldTenantID, executionlog.FieldExitCode, executionlog.FieldDurationMs:
			values[i] = new(sql.NullInt64)
		case executionlog.FieldID, executionlog.FieldScriptID, executionlog.FieldScriptName, executionlog.FieldClientID, executionlog.FieldScriptHash, executionlog.FieldTriggerType, executionlog.FieldStatus, executionlog.FieldOutput, executionlog.FieldErrorOutput, executionlog.FieldRejectionReason:
			values[i] = new(sql.NullString)
		case executionlog.FieldCreateTime, executionlog.FieldUpdateTime, executionlog.FieldDeleteTime, executionlog.FieldStartedAt, executionlog.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ExecutionLog fields.
func (_m *ExecutionLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case executionlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case executionlog.FieldCreateBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field create_by", values[i])
			} else if value.Valid {
				_m.CreateBy = new(uint32)
				*_m.CreateBy = uint32(value.Int64)
			}
		case executionlog.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				_m.CreateTime = new(time.Time)
				*_m.CreateTime = value.Time
			}
		case executionlog.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				_m.UpdateTime = new(time.Time)
				*_m.UpdateTime = value.Time
			}
		case executionlog.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				_m.DeleteTime = new(time.Time)
				*_m.DeleteTime = value.Time
			}
		case executionlog.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case executionlog.FieldScriptID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field script_id", values[i])
			} else if value.Valid {
				_m.ScriptID = value.String
			}
		case executionlog.FieldScriptName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field script_name", values[i])
			} else if value.Valid {
				_m.ScriptName = value.String
			}
		case executionlog.FieldClientID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value.Valid {
				_m.ClientID = value.String
			}
		case executionlog.FieldScriptHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field script_hash", values[i])
			} else if value.Valid {
				_m.ScriptHash = value.String
			}
		case executionlog.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = executionlog.TriggerType(value.String)
			}
		case executionlog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = executionlog.Status(value.String)
			}
		case executionlog.FieldExitCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field exit_code", values[i])
			} else if value.Valid {
				_m.ExitCode = new(int)
				*_m.ExitCode = int(value.Int64)
			}
		case executionlog.FieldOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field output", values[i])
			} else if value.Valid {
				_m.Output = value.String
			}
		case executionlog.FieldErrorOutput:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_output", values[i])
			} else if value.Valid {
				_m.ErrorOutput = value.String
			}
		case executionlog.FieldRejectionReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field rejection_reason", values[i])
			} else if value.Valid {
				_m.RejectionReason = value.String
			}
		case executionlog.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case executionlog.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case executionlog.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = new(int64)
				*_m.DurationMs = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ExecutionLog.
// This includes values selected through modifiers, order, etc.
func (_m *ExecutionLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ExecutionLog.
// Note that you need to call ExecutionLog.Unwrap() before calling this method if this ExecutionLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ExecutionLog) Update() *ExecutionLogUpdateOne {
	return NewExecutionLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ExecutionLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ExecutionLog) Unwrap() *ExecutionLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ExecutionLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ExecutionLog) String() string {
	var builder strings.Builder
	builder.WriteString("ExecutionLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreateBy; v != nil {
		builder.WriteString("create_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreateTime; v != nil {
		builder.WriteString("create_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdateTime; v != nil {
		builder.WriteString("update_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("script_id=")
	builder.WriteString(_m.ScriptID)
	builder.WriteString(", ")
	builder.WriteString("script_name=")
	builder.WriteString(_m.ScriptName)
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(_m.ClientID)
	builder.WriteString(", ")
	builder.WriteString("script_hash=")
	builder.WriteString(_m.ScriptHash)
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.ExitCode; v != nil {
		builder.WriteString("exit_code=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("output=")
	builder.WriteString(_m.Output)
	builder.WriteString(", ")
	builder.WriteString("error_output=")
	builder.WriteString(_m.ErrorOutput)
	builder.WriteString(", ")
	builder.WriteString("rejection_reason=")
	builder.WriteString(_m.RejectionReason)
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DurationMs; v != nil {
		builder.WriteString("duration_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ExecutionLogs is a parsable slice of ExecutionLog.
type ExecutionLogs []*ExecutionLog
