// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/executionlog"
)

// ExecutionLogCreate is the builder for creating a ExecutionLog entity.
type ExecutionLogCreate struct {
	config
	mutation *ExecutionLogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *ExecutionLogCreate) SetCreateBy(v uint32) *ExecutionLogCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableCreateBy(v *uint32) *ExecutionLogCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ExecutionLogCreate) SetCreateTime(v time.Time) *ExecutionLogCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableCreateTime(v *time.Time) *ExecutionLogCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ExecutionLogCreate) SetUpdateTime(v time.Time) *ExecutionLogCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableUpdateTime(v *time.Time) *ExecutionLogCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ExecutionLogCreate) SetDeleteTime(v time.Time) *ExecutionLogCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableDeleteTime(v *time.Time) *ExecutionLogCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ExecutionLogCreate) SetTenantID(v uint32) *ExecutionLogCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableTenantID(v *uint32) *ExecutionLogCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetScriptID sets the "script_id" field.
func (_c *ExecutionLogCreate) SetScriptID(v string) *ExecutionLogCreate {
	_c.mutation.SetScriptID(v)
	return _c
}

// SetScriptName sets the "script_name" field.
func (_c *ExecutionLogCreate) SetScriptName(v string) *ExecutionLogCreate {
	_c.mutation.SetScriptName(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ExecutionLogCreate) SetClientID(v string) *ExecutionLogCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetScriptHash sets the "script_hash" field.
func (_c *ExecutionLogCreate) SetScriptHash(v string) *ExecutionLogCreate {
	_c.mutation.SetScriptHash(v)
	return _c
}

// SetTriggerType sets the "trigger_type" field.
func (_c *ExecutionLogCreate) SetTriggerType(v executionlog.TriggerType) *ExecutionLogCreate {
	_c.mutation.SetTriggerType(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ExecutionLogCreate) SetStatus(v executionlog.Status) *ExecutionLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableStatus(v *executionlog.Status) *ExecutionLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExitCode sets the "exit_code" field.
func (_c *ExecutionLogCreate) SetExitCode(v int) *ExecutionLogCreate {
	_c.mutation.SetExitCode(v)
	return _c
}

// SetNillableExitCode sets the "exit_code" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableExitCode(v *int) *ExecutionLogCreate {
	if v != nil {
		_c.SetExitCode(*v)
	}
	return _c
}

// SetOutput sets the "output" field.
func (_c *ExecutionLogCreate) SetOutput(v string) *ExecutionLogCreate {
	_c.mutation.SetOutput(v)
	return _c
}

// SetNillableOutput sets the "output" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableOutput(v *string) *ExecutionLogCreate {
	if v != nil {
		_c.SetOutput(*v)
	}
	return _c
}

// SetErrorOutput sets the "error_output" field.
func (_c *ExecutionLogCreate) SetErrorOutput(v string) *ExecutionLogCreate {
	_c.mutation.SetErrorOutput(v)
	return _c
}

// SetNillableErrorOutput sets the "error_output" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableErrorOutput(v *string) *ExecutionLogCreate {
	if v != nil {
		_c.SetErrorOutput(*v)
	}
	return _c
}

// SetRejectionReason sets the "rejection_reason" field.
func (_c *ExecutionLogCreate) SetRejectionReason(v string) *ExecutionLogCreate {
	_c.mutation.SetRejectionReason(v)
	return _c
}

// SetNillableRejectionReason sets the "rejection_reason" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableRejectionReason(v *string) *ExecutionLogCreate {
	if v != nil {
		_c.SetRejectionReason(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ExecutionLogCreate) SetStartedAt(v time.Time) *ExecutionLogCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableStartedAt(v *time.Time) *ExecutionLogCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *ExecutionLogCreate) SetCompletedAt(v time.Time) *ExecutionLogCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableCompletedAt(v *time.Time) *ExecutionLogCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *ExecutionLogCreate) SetDurationMs(v int64) *ExecutionLogCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *ExecutionLogCreate) SetNillableDurationMs(v *int64) *ExecutionLogCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ExecutionLogCreate) SetID(v string) *ExecutionLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ExecutionLogMutation object of the builder.
func (_c *ExecutionLogCreate) Mutation() *ExecutionLogMutation {
	return _c.mutation
}

// Save creates the ExecutionLog in the database.
func (_c *ExecutionLogCreate) Save(ctx context.Context) (*ExecutionLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExecutionLogCreate) SaveX(ctx context.Context) *ExecutionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExecutionLogCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := executionlog.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := executionlog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExecutionLogCreate) check() error {
	if _, ok := _c.mutation.ScriptID(); !ok {
		return &ValidationError{Name: "script_id", err: errors.New(`ent: missing required field "ExecutionLog.script_id"`)}
	}
	if v, ok := _c.mutation.ScriptID(); ok {
		if err := executionlog.ScriptIDValidator(v); err != nil {
			return &ValidationError{Name: "script_id", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.script_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScriptName(); !ok {
		return &ValidationError{Name: "script_name", err: errors.New(`ent: missing required field "ExecutionLog.script_name"`)}
	}
	if v, ok := _c.mutation.ScriptName(); ok {
		if err := executionlog.ScriptNameValidator(v); err != nil {
			return &ValidationError{Name: "script_name", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.script_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "ExecutionLog.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := executionlog.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScriptHash(); !ok {
		return &ValidationError{Name: "script_hash", err: errors.New(`ent: missing required field "ExecutionLog.script_hash"`)}
	}
	if v, ok := _c.mutation.ScriptHash(); ok {
		if err := executionlog.ScriptHashValidator(v); err != nil {
			return &ValidationError{Name: "script_hash", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.script_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		return &ValidationError{Name: "trigger_type", err: errors.New(`ent: missing required field "ExecutionLog.trigger_type"`)}
	}
	if v, ok := _c.mutation.TriggerType(); ok {
		if err := executionlog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.trigger_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ExecutionLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := executionlog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RejectionReason(); ok {
		if err := executionlog.RejectionReasonValidator(v); err != nil {
			return &ValidationError{Name: "rejection_reason", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.rejection_reason": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := executionlog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ExecutionLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ExecutionLogCreate) sqlSave(ctx context.Context) (*ExecutionLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ExecutionLog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExecutionLogCreate) createSpec() (*ExecutionLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ExecutionLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(executionlog.Table, sqlgraph.NewFieldSpec(executionlog.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(executionlog.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(executionlog.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(executionlog.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(executionlog.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(executionlog.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ScriptID(); ok {
		_spec.SetField(executionlog.FieldScriptID, field.TypeString, value)
		_node.ScriptID = value
	}
	if value, ok := _c.mutation.ScriptName(); ok {
		_spec.SetField(executionlog.FieldScriptName, field.TypeString, value)
		_node.ScriptName = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(executionlog.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ScriptHash(); ok {
		_spec.SetField(executionlog.FieldScriptHash, field.TypeString, value)
		_node.ScriptHash = value
	}
	if value, ok := _c.mutation.TriggerType(); ok {
		_spec.SetField(executionlog.FieldTriggerType, field.TypeEnum, value)
		_node.TriggerType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(executionlog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.ExitCode(); ok {
		_spec.SetField(executionlog.FieldExitCode, field.TypeInt, value)
		_node.ExitCode = &value
	}
	if value, ok := _c.mutation.Output(); ok {
		_spec.SetField(executionlog.FieldOutput, field.TypeString, value)
		_node.Output = value
	}
	if value, ok := _c.mutation.ErrorOutput(); ok {
		_spec.SetField(executionlog.FieldErrorOutput, field.TypeString, value)
		_node.ErrorOutput = value
	}
	if value, ok := _c.mutation.RejectionReason(); ok {
		_spec.SetField(executionlog.FieldRejectionReason, field.TypeString, value)
		_node.RejectionReason = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(executionlog.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(executionlog.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(executionlog.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExecutionLog.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionLogUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionLogCreate) OnConflict(opts ...sql.ConflictOption) *ExecutionLogUpsertOne {
	_c.conflict = opts
	return &ExecutionLogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionLogCreate) OnConflictColumns(columns ...string) *ExecutionLogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionLogUpsertOne{
		create: _c,
	}
}

type (
	// ExecutionLogUpsertOne is the builder for "upsert"-ing
	//  one ExecutionLog node.
	ExecutionLogUpsertOne struct {
		create *ExecutionLogCreate
	}

	// ExecutionLogUpsert is the "OnConflict" setter.
	ExecutionLogUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *ExecutionLogUpsert) SetCreateBy(v uint32) *ExecutionLogUpsert {
	u.Set(executionlog.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateCreateBy() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *ExecutionLogUpsert) AddCreateBy(v uint32) *ExecutionLogUpsert {
	u.Add(executionlog.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ExecutionLogUpsert) ClearCreateBy() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ExecutionLogUpsert) SetUpdateTime(v time.Time) *ExecutionLogUpsert {
	u.Set(executionlog.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateUpdateTime() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ExecutionLogUpsert) ClearUpdateTime() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ExecutionLogUpsert) SetDeleteTime(v time.Time) *ExecutionLogUpsert {
	u.Set(executionlog.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateDeleteTime() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ExecutionLogUpsert) ClearDeleteTime() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldDeleteTime)
	return u
}

// SetScriptID sets the "script_id" field.
func (u *ExecutionLogUpsert) SetScriptID(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldScriptID, v)
	return u
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateScriptID() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldScriptID)
	return u
}

// SetScriptName sets the "script_name" field.
func (u *ExecutionLogUpsert) SetScriptName(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldScriptName, v)
	return u
}

// UpdateScriptName sets the "script_name" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateScriptName() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldScriptName)
	return u
}

// SetClientID sets the "client_id" field.
func (u *ExecutionLogUpsert) SetClientID(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateClientID() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldClientID)
	return u
}

// SetScriptHash sets the "script_hash" field.
func (u *ExecutionLogUpsert) SetScriptHash(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldScriptHash, v)
	return u
}

// UpdateScriptHash sets the "script_hash" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateScriptHash() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldScriptHash)
	return u
}

// SetTriggerType sets the "trigger_type" field.
func (u *ExecutionLogUpsert) SetTriggerType(v executionlog.TriggerType) *ExecutionLogUpsert {
	u.Set(executionlog.FieldTriggerType, v)
	return u
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateTriggerType() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldTriggerType)
	return u
}

// SetStatus sets the "status" field.
func (u *ExecutionLogUpsert) SetStatus(v executionlog.Status) *ExecutionLogUpsert {
	u.Set(executionlog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateStatus() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldStatus)
	return u
}

// SetExitCode sets the "exit_code" field.
func (u *ExecutionLogUpsert) SetExitCode(v int) *ExecutionLogUpsert {
	u.Set(executionlog.FieldExitCode, v)
	return u
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateExitCode() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldExitCode)
	return u
}

// AddExitCode adds v to the "exit_code" field.
func (u *ExecutionLogUpsert) AddExitCode(v int) *ExecutionLogUpsert {
	u.Add(executionlog.FieldExitCode, v)
	return u
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ExecutionLogUpsert) ClearExitCode() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldExitCode)
	return u
}

// SetOutput sets the "output" field.
func (u *ExecutionLogUpsert) SetOutput(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldOutput, v)
	return u
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateOutput() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldOutput)
	return u
}

// ClearOutput clears the value of the "output" field.
func (u *ExecutionLogUpsert) ClearOutput() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldOutput)
	return u
}

// SetErrorOutput sets the "error_output" field.
func (u *ExecutionLogUpsert) SetErrorOutput(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldErrorOutput, v)
	return u
}

// UpdateErrorOutput sets the "error_output" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateErrorOutput() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldErrorOutput)
	return u
}

// ClearErrorOutput clears the value of the "error_output" field.
func (u *ExecutionLogUpsert) ClearErrorOutput() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldErrorOutput)
	return u
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *ExecutionLogUpsert) SetRejectionReason(v string) *ExecutionLogUpsert {
	u.Set(executionlog.FieldRejectionReason, v)
	return u
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateRejectionReason() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldRejectionReason)
	return u
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *ExecutionLogUpsert) ClearRejectionReason() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldRejectionReason)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *ExecutionLogUpsert) SetStartedAt(v time.Time) *ExecutionLogUpsert {
	u.Set(executionlog.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateStartedAt() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ExecutionLogUpsert) ClearStartedAt() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldStartedAt)
	return u
}

// SetCompletedAt sets the "completed_at" field.
func (u *ExecutionLogUpsert) SetCompletedAt(v time.Time) *ExecutionLogUpsert {
	u.Set(executionlog.FieldCompletedAt, v)
	return u
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateCompletedAt() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldCompletedAt)
	return u
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ExecutionLogUpsert) ClearCompletedAt() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldCompletedAt)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *ExecutionLogUpsert) SetDurationMs(v int64) *ExecutionLogUpsert {
	u.Set(executionlog.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ExecutionLogUpsert) UpdateDurationMs() *ExecutionLogUpsert {
	u.SetExcluded(executionlog.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ExecutionLogUpsert) AddDurationMs(v int64) *ExecutionLogUpsert {
	u.Add(executionlog.FieldDurationMs, v)
	return u
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *ExecutionLogUpsert) ClearDurationMs() *ExecutionLogUpsert {
	u.SetNull(executionlog.FieldDurationMs)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(executionlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionLogUpsertOne) UpdateNewValues() *ExecutionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(executionlog.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(executionlog.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(executionlog.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExecutionLogUpsertOne) Ignore() *ExecutionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionLogUpsertOne) DoNothing() *ExecutionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionLogCreate.OnConflict
// documentation for more info.
func (u *ExecutionLogUpsertOne) Update(set func(*ExecutionLogUpsert)) *ExecutionLogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ExecutionLogUpsertOne) SetCreateBy(v uint32) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ExecutionLogUpsertOne) AddCreateBy(v uint32) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateCreateBy() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ExecutionLogUpsertOne) ClearCreateBy() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ExecutionLogUpsertOne) SetUpdateTime(v time.Time) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateUpdateTime() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ExecutionLogUpsertOne) ClearUpdateTime() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ExecutionLogUpsertOne) SetDeleteTime(v time.Time) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateDeleteTime() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ExecutionLogUpsertOne) ClearDeleteTime() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearDeleteTime()
	})
}

// SetScriptID sets the "script_id" field.
func (u *ExecutionLogUpsertOne) SetScriptID(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptID(v)
	})
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateScriptID() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptID()
	})
}

// SetScriptName sets the "script_name" field.
func (u *ExecutionLogUpsertOne) SetScriptName(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptName(v)
	})
}

// UpdateScriptName sets the "script_name" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateScriptName() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptName()
	})
}

// SetClientID sets the "client_id" field.
func (u *ExecutionLogUpsertOne) SetClientID(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateClientID() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateClientID()
	})
}

// SetScriptHash sets the "script_hash" field.
func (u *ExecutionLogUpsertOne) SetScriptHash(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptHash(v)
	})
}

// UpdateScriptHash sets the "script_hash" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateScriptHash() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptHash()
	})
}

// SetTriggerType sets the "trigger_type" field.
func (u *ExecutionLogUpsertOne) SetTriggerType(v executionlog.TriggerType) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetTriggerType(v)
	})
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateTriggerType() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateTriggerType()
	})
}

// SetStatus sets the "status" field.
func (u *ExecutionLogUpsertOne) SetStatus(v executionlog.Status) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateStatus() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateStatus()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *ExecutionLogUpsertOne) SetExitCode(v int) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *ExecutionLogUpsertOne) AddExitCode(v int) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateExitCode() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ExecutionLogUpsertOne) ClearExitCode() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearExitCode()
	})
}

// SetOutput sets the "output" field.
func (u *ExecutionLogUpsertOne) SetOutput(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateOutput() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *ExecutionLogUpsertOne) ClearOutput() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearOutput()
	})
}

// SetErrorOutput sets the "error_output" field.
func (u *ExecutionLogUpsertOne) SetErrorOutput(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetErrorOutput(v)
	})
}

// UpdateErrorOutput sets the "error_output" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateErrorOutput() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateErrorOutput()
	})
}

// ClearErrorOutput clears the value of the "error_output" field.
func (u *ExecutionLogUpsertOne) ClearErrorOutput() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearErrorOutput()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *ExecutionLogUpsertOne) SetRejectionReason(v string) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateRejectionReason() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *ExecutionLogUpsertOne) ClearRejectionReason() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearRejectionReason()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ExecutionLogUpsertOne) SetStartedAt(v time.Time) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateStartedAt() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ExecutionLogUpsertOne) ClearStartedAt() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ExecutionLogUpsertOne) SetCompletedAt(v time.Time) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateCompletedAt() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ExecutionLogUpsertOne) ClearCompletedAt() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *ExecutionLogUpsertOne) SetDurationMs(v int64) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ExecutionLogUpsertOne) AddDurationMs(v int64) *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ExecutionLogUpsertOne) UpdateDurationMs() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *ExecutionLogUpsertOne) ClearDurationMs() *ExecutionLogUpsertOne {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearDurationMs()
	})
}

// Exec executes the query.
func (u *ExecutionLogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExecutionLogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionLogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExecutionLogUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ExecutionLogUpsertOne.ID is not supported by MySQL driver. Use ExecutionLogUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExecutionLogUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExecutionLogCreateBulk is the builder for creating many ExecutionLog entities in bulk.
type ExecutionLogCreateBulk struct {
	config
	err      error
	builders []*ExecutionLogCreate
	conflict []sql.ConflictOption
}

// Save creates the ExecutionLog entities in the database.
func (_c *ExecutionLogCreateBulk) Save(ctx context.Context) ([]*ExecutionLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExecutionLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExecutionLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExecutionLogCreateBulk) SaveX(ctx context.Context) []*ExecutionLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExecutionLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExecutionLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExecutionLog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExecutionLogUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ExecutionLogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExecutionLogUpsertBulk {
	_c.conflict = opts
	return &ExecutionLogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExecutionLogCreateBulk) OnConflictColumns(columns ...string) *ExecutionLogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExecutionLogUpsertBulk{
		create: _c,
	}
}

// ExecutionLogUpsertBulk is the builder for "upsert"-ing
// a bulk of ExecutionLog nodes.
type ExecutionLogUpsertBulk struct {
	create *ExecutionLogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(executionlog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ExecutionLogUpsertBulk) UpdateNewValues() *ExecutionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(executionlog.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(executionlog.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(executionlog.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExecutionLog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExecutionLogUpsertBulk) Ignore() *ExecutionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExecutionLogUpsertBulk) DoNothing() *ExecutionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExecutionLogCreateBulk.OnConflict
// documentation for more info.
func (u *ExecutionLogUpsertBulk) Update(set func(*ExecutionLogUpsert)) *ExecutionLogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExecutionLogUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ExecutionLogUpsertBulk) SetCreateBy(v uint32) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ExecutionLogUpsertBulk) AddCreateBy(v uint32) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateCreateBy() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ExecutionLogUpsertBulk) ClearCreateBy() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ExecutionLogUpsertBulk) SetUpdateTime(v time.Time) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateUpdateTime() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ExecutionLogUpsertBulk) ClearUpdateTime() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ExecutionLogUpsertBulk) SetDeleteTime(v time.Time) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateDeleteTime() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ExecutionLogUpsertBulk) ClearDeleteTime() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearDeleteTime()
	})
}

// SetScriptID sets the "script_id" field.
func (u *ExecutionLogUpsertBulk) SetScriptID(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptID(v)
	})
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateScriptID() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptID()
	})
}

// SetScriptName sets the "script_name" field.
func (u *ExecutionLogUpsertBulk) SetScriptName(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptName(v)
	})
}

// UpdateScriptName sets the "script_name" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateScriptName() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptName()
	})
}

// SetClientID sets the "client_id" field.
func (u *ExecutionLogUpsertBulk) SetClientID(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateClientID() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateClientID()
	})
}

// SetScriptHash sets the "script_hash" field.
func (u *ExecutionLogUpsertBulk) SetScriptHash(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetScriptHash(v)
	})
}

// UpdateScriptHash sets the "script_hash" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateScriptHash() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateScriptHash()
	})
}

// SetTriggerType sets the "trigger_type" field.
func (u *ExecutionLogUpsertBulk) SetTriggerType(v executionlog.TriggerType) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetTriggerType(v)
	})
}

// UpdateTriggerType sets the "trigger_type" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateTriggerType() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateTriggerType()
	})
}

// SetStatus sets the "status" field.
func (u *ExecutionLogUpsertBulk) SetStatus(v executionlog.Status) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateStatus() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateStatus()
	})
}

// SetExitCode sets the "exit_code" field.
func (u *ExecutionLogUpsertBulk) SetExitCode(v int) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetExitCode(v)
	})
}

// AddExitCode adds v to the "exit_code" field.
func (u *ExecutionLogUpsertBulk) AddExitCode(v int) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddExitCode(v)
	})
}

// UpdateExitCode sets the "exit_code" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateExitCode() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateExitCode()
	})
}

// ClearExitCode clears the value of the "exit_code" field.
func (u *ExecutionLogUpsertBulk) ClearExitCode() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearExitCode()
	})
}

// SetOutput sets the "output" field.
func (u *ExecutionLogUpsertBulk) SetOutput(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateOutput() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *ExecutionLogUpsertBulk) ClearOutput() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearOutput()
	})
}

// SetErrorOutput sets the "error_output" field.
func (u *ExecutionLogUpsertBulk) SetErrorOutput(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetErrorOutput(v)
	})
}

// UpdateErrorOutput sets the "error_output" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateErrorOutput() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateErrorOutput()
	})
}

// ClearErrorOutput clears the value of the "error_output" field.
func (u *ExecutionLogUpsertBulk) ClearErrorOutput() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearErrorOutput()
	})
}

// SetRejectionReason sets the "rejection_reason" field.
func (u *ExecutionLogUpsertBulk) SetRejectionReason(v string) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetRejectionReason(v)
	})
}

// UpdateRejectionReason sets the "rejection_reason" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateRejectionReason() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateRejectionReason()
	})
}

// ClearRejectionReason clears the value of the "rejection_reason" field.
func (u *ExecutionLogUpsertBulk) ClearRejectionReason() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearRejectionReason()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *ExecutionLogUpsertBulk) SetStartedAt(v time.Time) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateStartedAt() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *ExecutionLogUpsertBulk) ClearStartedAt() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearStartedAt()
	})
}

// SetCompletedAt sets the "completed_at" field.
func (u *ExecutionLogUpsertBulk) SetCompletedAt(v time.Time) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetCompletedAt(v)
	})
}

// UpdateCompletedAt sets the "completed_at" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateCompletedAt() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateCompletedAt()
	})
}

// ClearCompletedAt clears the value of the "completed_at" field.
func (u *ExecutionLogUpsertBulk) ClearCompletedAt() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearCompletedAt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *ExecutionLogUpsertBulk) SetDurationMs(v int64) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *ExecutionLogUpsertBulk) AddDurationMs(v int64) *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *ExecutionLogUpsertBulk) UpdateDurationMs() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.UpdateDurationMs()
	})
}

// ClearDurationMs clears the value of the "duration_ms" field.
func (u *ExecutionLogUpsertBulk) ClearDurationMs() *ExecutionLogUpsertBulk {
	return u.Update(func(s *ExecutionLogUpsert) {
		s.ClearDurationMs()
	})
}

// Exec executes the query.
func (u *ExecutionLogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExecutionLogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExecutionLogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExecutionLogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
