// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/scriptassignment"
)

// ScriptAssignmentUpdate is the builder for updating ScriptAssignment entities.
type ScriptAssignmentUpdate struct {
	config
	hooks     []Hook
	mutation  *ScriptAssignmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ScriptAssignmentUpdate builder.
func (_u *ScriptAssignmentUpdate) Where(ps ...predicate.ScriptAssignment) *ScriptAssignmentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ScriptAssignmentUpdate) SetCreateBy(v uint32) *ScriptAssignmentUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ScriptAssignmentUpdate) SetNillableCreateBy(v *uint32) *ScriptAssignmentUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ScriptAssignmentUpdate) AddCreateBy(v int32) *ScriptAssignmentUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ScriptAssignmentUpdate) ClearCreateBy() *ScriptAssignmentUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScriptAssignmentUpdate) SetUpdateTime(v time.Time) *ScriptAssignmentUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ScriptAssignmentUpdate) SetNillableUpdateTime(v *time.Time) *ScriptAssignmentUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ScriptAssignmentUpdate) ClearUpdateTime() *ScriptAssignmentUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ScriptAssignmentUpdate) SetDeleteTime(v time.Time) *ScriptAssignmentUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ScriptAssignmentUpdate) SetNillableDeleteTime(v *time.Time) *ScriptAssignmentUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ScriptAssignmentUpdate) ClearDeleteTime() *ScriptAssignmentUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *ScriptAssignmentUpdate) SetScriptID(v string) *ScriptAssignmentUpdate {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *ScriptAssignmentUpdate) SetNillableScriptID(v *string) *ScriptAssignmentUpdate {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ScriptAssignmentUpdate) SetClientID(v string) *ScriptAssignmentUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ScriptAssignmentUpdate) SetNillableClientID(v *string) *ScriptAssignmentUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// Mutation returns the ScriptAssignmentMutation object of the builder.
func (_u *ScriptAssignmentUpdate) Mutation() *ScriptAssignmentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptAssignmentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptAssignmentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptAssignmentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptAssignmentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptAssignmentUpdate) check() error {
	if v, ok := _u.mutation.ScriptID(); ok {
		if err := scriptassignment.ScriptIDValidator(v); err != nil {
			return &ValidationError{Name: "script_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.script_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := scriptassignment.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.client_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScriptAssignmentUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScriptAssignmentUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScriptAssignmentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptassignment.Table, scriptassignment.Columns, sqlgraph.NewFieldSpec(scriptassignment.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(scriptassignment.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(scriptassignment.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(scriptassignment.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(scriptassignment.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(scriptassignment.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(scriptassignment.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(scriptassignment.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(scriptassignment.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(scriptassignment.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ScriptID(); ok {
		_spec.SetField(scriptassignment.FieldScriptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(scriptassignment.FieldClientID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptAssignmentUpdateOne is the builder for updating a single ScriptAssignment entity.
type ScriptAssignmentUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ScriptAssignmentMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ScriptAssignmentUpdateOne) SetCreateBy(v uint32) *ScriptAssignmentUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ScriptAssignmentUpdateOne) SetNillableCreateBy(v *uint32) *ScriptAssignmentUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ScriptAssignmentUpdateOne) AddCreateBy(v int32) *ScriptAssignmentUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ScriptAssignmentUpdateOne) ClearCreateBy() *ScriptAssignmentUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScriptAssignmentUpdateOne) SetUpdateTime(v time.Time) *ScriptAssignmentUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ScriptAssignmentUpdateOne) SetNillableUpdateTime(v *time.Time) *ScriptAssignmentUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ScriptAssignmentUpdateOne) ClearUpdateTime() *ScriptAssignmentUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ScriptAssignmentUpdateOne) SetDeleteTime(v time.Time) *ScriptAssignmentUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ScriptAssignmentUpdateOne) SetNillableDeleteTime(v *time.Time) *ScriptAssignmentUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ScriptAssignmentUpdateOne) ClearDeleteTime() *ScriptAssignmentUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetScriptID sets the "script_id" field.
func (_u *ScriptAssignmentUpdateOne) SetScriptID(v string) *ScriptAssignmentUpdateOne {
	_u.mutation.SetScriptID(v)
	return _u
}

// SetNillableScriptID sets the "script_id" field if the given value is not nil.
func (_u *ScriptAssignmentUpdateOne) SetNillableScriptID(v *string) *ScriptAssignmentUpdateOne {
	if v != nil {
		_u.SetScriptID(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *ScriptAssignmentUpdateOne) SetClientID(v string) *ScriptAssignmentUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *ScriptAssignmentUpdateOne) SetNillableClientID(v *string) *ScriptAssignmentUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// Mutation returns the ScriptAssignmentMutation object of the builder.
func (_u *ScriptAssignmentUpdateOne) Mutation() *ScriptAssignmentMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScriptAssignmentUpdate builder.
func (_u *ScriptAssignmentUpdateOne) Where(ps ...predicate.ScriptAssignment) *ScriptAssignmentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptAssignmentUpdateOne) Select(field string, fields ...string) *ScriptAssignmentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ScriptAssignment entity.
func (_u *ScriptAssignmentUpdateOne) Save(ctx context.Context) (*ScriptAssignment, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptAssignmentUpdateOne) SaveX(ctx context.Context) *ScriptAssignment {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptAssignmentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptAssignmentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptAssignmentUpdateOne) check() error {
	if v, ok := _u.mutation.ScriptID(); ok {
		if err := scriptassignment.ScriptIDValidator(v); err != nil {
			return &ValidationError{Name: "script_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.script_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientID(); ok {
		if err := scriptassignment.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.client_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScriptAssignmentUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScriptAssignmentUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScriptAssignmentUpdateOne) sqlSave(ctx context.Context) (_node *ScriptAssignment, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(scriptassignment.Table, scriptassignment.Columns, sqlgraph.NewFieldSpec(scriptassignment.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ScriptAssignment.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, scriptassignment.FieldID)
		for _, f := range fields {
			if !scriptassignment.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != scriptassignment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(scriptassignment.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(scriptassignment.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(scriptassignment.FieldCreateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(scriptassignment.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(scriptassignment.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(scriptassignment.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(scriptassignment.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(scriptassignment.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(scriptassignment.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.ScriptID(); ok {
		_spec.SetField(scriptassignment.FieldScriptID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(scriptassignment.FieldClientID, field.TypeString, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &ScriptAssignment{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{scriptassignment.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
