// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/script"
)

// ScriptCreate is the builder for creating a Script entity.
type ScriptCreate struct {
	config
	mutation *ScriptMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *ScriptCreate) SetCreateBy(v uint32) *ScriptCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCreateBy(v *uint32) *ScriptCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *ScriptCreate) SetUpdateBy(v uint32) *ScriptCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUpdateBy(v *uint32) *ScriptCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ScriptCreate) SetCreateTime(v time.Time) *ScriptCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableCreateTime(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ScriptCreate) SetUpdateTime(v time.Time) *ScriptCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableUpdateTime(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ScriptCreate) SetDeleteTime(v time.Time) *ScriptCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDeleteTime(v *time.Time) *ScriptCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ScriptCreate) SetTenantID(v uint32) *ScriptCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableTenantID(v *uint32) *ScriptCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ScriptCreate) SetName(v string) *ScriptCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *ScriptCreate) SetDescription(v string) *ScriptCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableDescription(v *string) *ScriptCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetScriptType sets the "script_type" field.
func (_c *ScriptCreate) SetScriptType(v script.ScriptType) *ScriptCreate {
	_c.mutation.SetScriptType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ScriptCreate) SetContent(v string) *ScriptCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetContentHash sets the "content_hash" field.
func (_c *ScriptCreate) SetContentHash(v string) *ScriptCreate {
	_c.mutation.SetContentHash(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *ScriptCreate) SetVersion(v int) *ScriptCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableVersion(v *int) *ScriptCreate {
	if v != nil {
		_c.SetVersion(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *ScriptCreate) SetEnabled(v bool) *ScriptCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *ScriptCreate) SetNillableEnabled(v *bool) *ScriptCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ScriptCreate) SetID(v string) *ScriptCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScriptMutation object of the builder.
func (_c *ScriptCreate) Mutation() *ScriptMutation {
	return _c.mutation
}

// Save creates the Script in the database.
func (_c *ScriptCreate) Save(ctx context.Context) (*Script, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptCreate) SaveX(ctx context.Context) *Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := script.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	if _, ok := _c.mutation.Version(); !ok {
		v := script.DefaultVersion
		_c.mutation.SetVersion(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := script.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Script.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := script.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Script.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScriptType(); !ok {
		return &ValidationError{Name: "script_type", err: errors.New(`ent: missing required field "Script.script_type"`)}
	}
	if v, ok := _c.mutation.ScriptType(); ok {
		if err := script.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "Script.script_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Script.content"`)}
	}
	if _, ok := _c.mutation.ContentHash(); !ok {
		return &ValidationError{Name: "content_hash", err: errors.New(`ent: missing required field "Script.content_hash"`)}
	}
	if v, ok := _c.mutation.ContentHash(); ok {
		if err := script.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Script.content_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "Script.version"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Script.enabled"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := script.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Script.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScriptCreate) sqlSave(ctx context.Context) (*Script, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Script.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptCreate) createSpec() (*Script, *sqlgraph.CreateSpec) {
	var (
		_node = &Script{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(script.Table, sqlgraph.NewFieldSpec(script.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(script.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(script.FieldUpdateBy, field.TypeUint32, value)
		_node.UpdateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(script.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(script.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(script.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(script.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ScriptType(); ok {
		_spec.SetField(script.FieldScriptType, field.TypeEnum, value)
		_node.ScriptType = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(script.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.ContentHash(); ok {
		_spec.SetField(script.FieldContentHash, field.TypeString, value)
		_node.ContentHash = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(script.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(script.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Script.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScriptUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ScriptCreate) OnConflict(opts ...sql.ConflictOption) *ScriptUpsertOne {
	_c.conflict = opts
	return &ScriptUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Script.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScriptCreate) OnConflictColumns(columns ...string) *ScriptUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScriptUpsertOne{
		create: _c,
	}
}

type (
	// ScriptUpsertOne is the builder for "upsert"-ing
	//  one Script node.
	ScriptUpsertOne struct {
		create *ScriptCreate
	}

	// ScriptUpsert is the "OnConflict" setter.
	ScriptUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *ScriptUpsert) SetCreateBy(v uint32) *ScriptUpsert {
	u.Set(script.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateCreateBy() *ScriptUpsert {
	u.SetExcluded(script.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptUpsert) AddCreateBy(v uint32) *ScriptUpsert {
	u.Add(script.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptUpsert) ClearCreateBy() *ScriptUpsert {
	u.SetNull(script.FieldCreateBy)
	return u
}

// SetUpdateBy sets the "update_by" field.
func (u *ScriptUpsert) SetUpdateBy(v uint32) *ScriptUpsert {
	u.Set(script.FieldUpdateBy, v)
	return u
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateUpdateBy() *ScriptUpsert {
	u.SetExcluded(script.FieldUpdateBy)
	return u
}

// AddUpdateBy adds v to the "update_by" field.
func (u *ScriptUpsert) AddUpdateBy(v uint32) *ScriptUpsert {
	u.Add(script.FieldUpdateBy, v)
	return u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *ScriptUpsert) ClearUpdateBy() *ScriptUpsert {
	u.SetNull(script.FieldUpdateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptUpsert) SetUpdateTime(v time.Time) *ScriptUpsert {
	u.Set(script.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateUpdateTime() *ScriptUpsert {
	u.SetExcluded(script.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptUpsert) ClearUpdateTime() *ScriptUpsert {
	u.SetNull(script.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptUpsert) SetDeleteTime(v time.Time) *ScriptUpsert {
	u.Set(script.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateDeleteTime() *ScriptUpsert {
	u.SetExcluded(script.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptUpsert) ClearDeleteTime() *ScriptUpsert {
	u.SetNull(script.FieldDeleteTime)
	return u
}

// SetName sets the "name" field.
func (u *ScriptUpsert) SetName(v string) *ScriptUpsert {
	u.Set(script.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateName() *ScriptUpsert {
	u.SetExcluded(script.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *ScriptUpsert) SetDescription(v string) *ScriptUpsert {
	u.Set(script.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateDescription() *ScriptUpsert {
	u.SetExcluded(script.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *ScriptUpsert) ClearDescription() *ScriptUpsert {
	u.SetNull(script.FieldDescription)
	return u
}

// SetScriptType sets the "script_type" field.
func (u *ScriptUpsert) SetScriptType(v script.ScriptType) *ScriptUpsert {
	u.Set(script.FieldScriptType, v)
	return u
}

// UpdateScriptType sets the "script_type" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateScriptType() *ScriptUpsert {
	u.SetExcluded(script.FieldScriptType)
	return u
}

// SetContent sets the "content" field.
func (u *ScriptUpsert) SetContent(v string) *ScriptUpsert {
	u.Set(script.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateContent() *ScriptUpsert {
	u.SetExcluded(script.FieldContent)
	return u
}

// SetContentHash sets the "content_hash" field.
func (u *ScriptUpsert) SetContentHash(v string) *ScriptUpsert {
	u.Set(script.FieldContentHash, v)
	return u
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateContentHash() *ScriptUpsert {
	u.SetExcluded(script.FieldContentHash)
	return u
}

// SetVersion sets the "version" field.
func (u *ScriptUpsert) SetVersion(v int) *ScriptUpsert {
	u.Set(script.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateVersion() *ScriptUpsert {
	u.SetExcluded(script.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *ScriptUpsert) AddVersion(v int) *ScriptUpsert {
	u.Add(script.FieldVersion, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *ScriptUpsert) SetEnabled(v bool) *ScriptUpsert {
	u.Set(script.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ScriptUpsert) UpdateEnabled() *ScriptUpsert {
	u.SetExcluded(script.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Script.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(script.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScriptUpsertOne) UpdateNewValues() *ScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(script.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(script.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(script.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Script.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScriptUpsertOne) Ignore() *ScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScriptUpsertOne) DoNothing() *ScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScriptCreate.OnConflict
// documentation for more info.
func (u *ScriptUpsertOne) Update(set func(*ScriptUpsert)) *ScriptUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScriptUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ScriptUpsertOne) SetCreateBy(v uint32) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptUpsertOne) AddCreateBy(v uint32) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateCreateBy() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptUpsertOne) ClearCreateBy() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *ScriptUpsertOne) SetUpdateBy(v uint32) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *ScriptUpsertOne) AddUpdateBy(v uint32) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateUpdateBy() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *ScriptUpsertOne) ClearUpdateBy() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptUpsertOne) SetUpdateTime(v time.Time) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateUpdateTime() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptUpsertOne) ClearUpdateTime() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptUpsertOne) SetDeleteTime(v time.Time) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateDeleteTime() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptUpsertOne) ClearDeleteTime() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *ScriptUpsertOne) SetName(v string) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateName() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ScriptUpsertOne) SetDescription(v string) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateDescription() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ScriptUpsertOne) ClearDescription() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearDescription()
	})
}

// SetScriptType sets the "script_type" field.
func (u *ScriptUpsertOne) SetScriptType(v script.ScriptType) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetScriptType(v)
	})
}

// UpdateScriptType sets the "script_type" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateScriptType() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateScriptType()
	})
}

// SetContent sets the "content" field.
func (u *ScriptUpsertOne) SetContent(v string) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateContent() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateContent()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *ScriptUpsertOne) SetContentHash(v string) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateContentHash() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateContentHash()
	})
}

// SetVersion sets the "version" field.
func (u *ScriptUpsertOne) SetVersion(v int) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ScriptUpsertOne) AddVersion(v int) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateVersion() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ScriptUpsertOne) SetEnabled(v bool) *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ScriptUpsertOne) UpdateEnabled() *ScriptUpsertOne {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ScriptUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScriptCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScriptUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScriptUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ScriptUpsertOne.ID is not supported by MySQL driver. Use ScriptUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScriptUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScriptCreateBulk is the builder for creating many Script entities in bulk.
type ScriptCreateBulk struct {
	config
	err      error
	builders []*ScriptCreate
	conflict []sql.ConflictOption
}

// Save creates the Script entities in the database.
func (_c *ScriptCreateBulk) Save(ctx context.Context) ([]*Script, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Script, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptCreateBulk) SaveX(ctx context.Context) []*Script {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Script.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScriptUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ScriptCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScriptUpsertBulk {
	_c.conflict = opts
	return &ScriptUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Script.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScriptCreateBulk) OnConflictColumns(columns ...string) *ScriptUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScriptUpsertBulk{
		create: _c,
	}
}

// ScriptUpsertBulk is the builder for "upsert"-ing
// a bulk of Script nodes.
type ScriptUpsertBulk struct {
	create *ScriptCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Script.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(script.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScriptUpsertBulk) UpdateNewValues() *ScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(script.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(script.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(script.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Script.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScriptUpsertBulk) Ignore() *ScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScriptUpsertBulk) DoNothing() *ScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScriptCreateBulk.OnConflict
// documentation for more info.
func (u *ScriptUpsertBulk) Update(set func(*ScriptUpsert)) *ScriptUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScriptUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ScriptUpsertBulk) SetCreateBy(v uint32) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptUpsertBulk) AddCreateBy(v uint32) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateCreateBy() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptUpsertBulk) ClearCreateBy() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateBy sets the "update_by" field.
func (u *ScriptUpsertBulk) SetUpdateBy(v uint32) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetUpdateBy(v)
	})
}

// AddUpdateBy adds v to the "update_by" field.
func (u *ScriptUpsertBulk) AddUpdateBy(v uint32) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.AddUpdateBy(v)
	})
}

// UpdateUpdateBy sets the "update_by" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateUpdateBy() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateUpdateBy()
	})
}

// ClearUpdateBy clears the value of the "update_by" field.
func (u *ScriptUpsertBulk) ClearUpdateBy() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearUpdateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptUpsertBulk) SetUpdateTime(v time.Time) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateUpdateTime() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptUpsertBulk) ClearUpdateTime() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptUpsertBulk) SetDeleteTime(v time.Time) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateDeleteTime() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptUpsertBulk) ClearDeleteTime() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearDeleteTime()
	})
}

// SetName sets the "name" field.
func (u *ScriptUpsertBulk) SetName(v string) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateName() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *ScriptUpsertBulk) SetDescription(v string) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateDescription() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *ScriptUpsertBulk) ClearDescription() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.ClearDescription()
	})
}

// SetScriptType sets the "script_type" field.
func (u *ScriptUpsertBulk) SetScriptType(v script.ScriptType) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetScriptType(v)
	})
}

// UpdateScriptType sets the "script_type" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateScriptType() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateScriptType()
	})
}

// SetContent sets the "content" field.
func (u *ScriptUpsertBulk) SetContent(v string) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateContent() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateContent()
	})
}

// SetContentHash sets the "content_hash" field.
func (u *ScriptUpsertBulk) SetContentHash(v string) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetContentHash(v)
	})
}

// UpdateContentHash sets the "content_hash" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateContentHash() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateContentHash()
	})
}

// SetVersion sets the "version" field.
func (u *ScriptUpsertBulk) SetVersion(v int) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *ScriptUpsertBulk) AddVersion(v int) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateVersion() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateVersion()
	})
}

// SetEnabled sets the "enabled" field.
func (u *ScriptUpsertBulk) SetEnabled(v bool) *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *ScriptUpsertBulk) UpdateEnabled() *ScriptUpsertBulk {
	return u.Update(func(s *ScriptUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *ScriptUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScriptCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScriptCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScriptUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
