// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/script"
)

// ScriptUpdate is the builder for updating Script entities.
type ScriptUpdate struct {
	config
	hooks     []Hook
	mutation  *ScriptMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdate) Where(ps ...predicate.Script) *ScriptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *ScriptUpdate) SetCreateBy(v uint32) *ScriptUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableCreateBy(v *uint32) *ScriptUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ScriptUpdate) AddCreateBy(v int32) *ScriptUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ScriptUpdate) ClearCreateBy() *ScriptUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ScriptUpdate) SetUpdateBy(v uint32) *ScriptUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableUpdateBy(v *uint32) *ScriptUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ScriptUpdate) AddUpdateBy(v int32) *ScriptUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ScriptUpdate) ClearUpdateBy() *ScriptUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScriptUpdate) SetUpdateTime(v time.Time) *ScriptUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableUpdateTime(v *time.Time) *ScriptUpdate {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ScriptUpdate) ClearUpdateTime() *ScriptUpdate {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ScriptUpdate) SetDeleteTime(v time.Time) *ScriptUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableDeleteTime(v *time.Time) *ScriptUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ScriptUpdate) ClearDeleteTime() *ScriptUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptUpdate) SetName(v string) *ScriptUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableName(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptUpdate) SetDescription(v string) *ScriptUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableDescription(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScriptUpdate) ClearDescription() *ScriptUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetScriptType sets the "script_type" field.
func (_u *ScriptUpdate) SetScriptType(v script.ScriptType) *ScriptUpdate {
	_u.mutation.SetScriptType(v)
	return _u
}

// SetNillableScriptType sets the "script_type" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableScriptType(v *script.ScriptType) *ScriptUpdate {
	if v != nil {
		_u.SetScriptType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ScriptUpdate) SetContent(v string) *ScriptUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableContent(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *ScriptUpdate) SetContentHash(v string) *ScriptUpdate {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableContentHash(v *string) *ScriptUpdate {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScriptUpdate) SetVersion(v int) *ScriptUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableVersion(v *int) *ScriptUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ScriptUpdate) AddVersion(v int) *ScriptUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScriptUpdate) SetEnabled(v bool) *ScriptUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScriptUpdate) SetNillableEnabled(v *bool) *ScriptUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdate) Mutation() *ScriptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ScriptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ScriptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := script.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Script.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScriptType(); ok {
		if err := script.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "Script.script_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := script.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Script.content_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScriptUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScriptUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScriptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(script.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(script.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(script.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(script.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(script.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(script.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(script.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(script.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(script.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(script.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(script.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(script.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(script.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ScriptType(); ok {
		_spec.SetField(script.FieldScriptType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(script.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(script.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(script.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(script.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(script.FieldEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ScriptUpdateOne is the builder for updating a single Script entity.
type ScriptUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ScriptMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetCreateBy sets the "create_by" field.
func (_u *ScriptUpdateOne) SetCreateBy(v uint32) *ScriptUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableCreateBy(v *uint32) *ScriptUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *ScriptUpdateOne) AddCreateBy(v int32) *ScriptUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *ScriptUpdateOne) ClearCreateBy() *ScriptUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *ScriptUpdateOne) SetUpdateBy(v uint32) *ScriptUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableUpdateBy(v *uint32) *ScriptUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *ScriptUpdateOne) AddUpdateBy(v int32) *ScriptUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *ScriptUpdateOne) ClearUpdateBy() *ScriptUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *ScriptUpdateOne) SetUpdateTime(v time.Time) *ScriptUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableUpdateTime(v *time.Time) *ScriptUpdateOne {
	if v != nil {
		_u.SetUpdateTime(*v)
	}
	return _u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (_u *ScriptUpdateOne) ClearUpdateTime() *ScriptUpdateOne {
	_u.mutation.ClearUpdateTime()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *ScriptUpdateOne) SetDeleteTime(v time.Time) *ScriptUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableDeleteTime(v *time.Time) *ScriptUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *ScriptUpdateOne) ClearDeleteTime() *ScriptUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetName sets the "name" field.
func (_u *ScriptUpdateOne) SetName(v string) *ScriptUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableName(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *ScriptUpdateOne) SetDescription(v string) *ScriptUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableDescription(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *ScriptUpdateOne) ClearDescription() *ScriptUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetScriptType sets the "script_type" field.
func (_u *ScriptUpdateOne) SetScriptType(v script.ScriptType) *ScriptUpdateOne {
	_u.mutation.SetScriptType(v)
	return _u
}

// SetNillableScriptType sets the "script_type" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableScriptType(v *script.ScriptType) *ScriptUpdateOne {
	if v != nil {
		_u.SetScriptType(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ScriptUpdateOne) SetContent(v string) *ScriptUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableContent(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetContentHash sets the "content_hash" field.
func (_u *ScriptUpdateOne) SetContentHash(v string) *ScriptUpdateOne {
	_u.mutation.SetContentHash(v)
	return _u
}

// SetNillableContentHash sets the "content_hash" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableContentHash(v *string) *ScriptUpdateOne {
	if v != nil {
		_u.SetContentHash(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *ScriptUpdateOne) SetVersion(v int) *ScriptUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableVersion(v *int) *ScriptUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *ScriptUpdateOne) AddVersion(v int) *ScriptUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ScriptUpdateOne) SetEnabled(v bool) *ScriptUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ScriptUpdateOne) SetNillableEnabled(v *bool) *ScriptUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// Mutation returns the ScriptMutation object of the builder.
func (_u *ScriptUpdateOne) Mutation() *ScriptMutation {
	return _u.mutation
}

// Where appends a list predicates to the ScriptUpdate builder.
func (_u *ScriptUpdateOne) Where(ps ...predicate.Script) *ScriptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ScriptUpdateOne) Select(field string, fields ...string) *ScriptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Script entity.
func (_u *ScriptUpdateOne) Save(ctx context.Context) (*Script, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ScriptUpdateOne) SaveX(ctx context.Context) *Script {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ScriptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ScriptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ScriptUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := script.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Script.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := script.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Script.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScriptType(); ok {
		if err := script.ScriptTypeValidator(v); err != nil {
			return &ValidationError{Name: "script_type", err: fmt.Errorf(`ent: validator failed for field "Script.script_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContentHash(); ok {
		if err := script.ContentHashValidator(v); err != nil {
			return &ValidationError{Name: "content_hash", err: fmt.Errorf(`ent: validator failed for field "Script.content_hash": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *ScriptUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ScriptUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *ScriptUpdateOne) sqlSave(ctx context.Context) (_node *Script, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(script.Table, script.Columns, sqlgraph.NewFieldSpec(script.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Script.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, script.FieldID)
		for _, f := range fields {
			if !script.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != script.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(script.FieldCreateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(script.FieldCreateBy, field.TypeUint32, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(script.FieldCreateBy, field.TypeUint32)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(script.FieldUpdateBy, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(script.FieldUpdateBy, field.TypeUint32, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(script.FieldUpdateBy, field.TypeUint32)
	}
	if _u.mutation.CreateTimeCleared() {
		_spec.ClearField(script.FieldCreateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(script.FieldUpdateTime, field.TypeTime, value)
	}
	if _u.mutation.UpdateTimeCleared() {
		_spec.ClearField(script.FieldUpdateTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(script.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(script.FieldDeleteTime, field.TypeTime)
	}
	if _u.mutation.TenantIDCleared() {
		_spec.ClearField(script.FieldTenantID, field.TypeUint32)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(script.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(script.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(script.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ScriptType(); ok {
		_spec.SetField(script.FieldScriptType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(script.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContentHash(); ok {
		_spec.SetField(script.FieldContentHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(script.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(script.FieldVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(script.FieldEnabled, field.TypeBool, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Script{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{script.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
