// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-executor/internal/data/ent/scriptassignment"
)

// ScriptAssignmentCreate is the builder for creating a ScriptAssignment entity.
type ScriptAssignmentCreate struct {
	config
	mutation *ScriptAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreateBy sets the "create_by" field.
func (_c *ScriptAssignmentCreate) SetCreateBy(v uint32) *ScriptAssignmentCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *ScriptAssignmentCreate) SetNillableCreateBy(v *uint32) *ScriptAssignmentCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetCreateTime sets the "create_time" field.
func (_c *ScriptAssignmentCreate) SetCreateTime(v time.Time) *ScriptAssignmentCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *ScriptAssignmentCreate) SetNillableCreateTime(v *time.Time) *ScriptAssignmentCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *ScriptAssignmentCreate) SetUpdateTime(v time.Time) *ScriptAssignmentCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *ScriptAssignmentCreate) SetNillableUpdateTime(v *time.Time) *ScriptAssignmentCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *ScriptAssignmentCreate) SetDeleteTime(v time.Time) *ScriptAssignmentCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *ScriptAssignmentCreate) SetNillableDeleteTime(v *time.Time) *ScriptAssignmentCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *ScriptAssignmentCreate) SetTenantID(v uint32) *ScriptAssignmentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *ScriptAssignmentCreate) SetNillableTenantID(v *uint32) *ScriptAssignmentCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetScriptID sets the "script_id" field.
func (_c *ScriptAssignmentCreate) SetScriptID(v string) *ScriptAssignmentCreate {
	_c.mutation.SetScriptID(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *ScriptAssignmentCreate) SetClientID(v string) *ScriptAssignmentCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ScriptAssignmentCreate) SetID(v string) *ScriptAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the ScriptAssignmentMutation object of the builder.
func (_c *ScriptAssignmentCreate) Mutation() *ScriptAssignmentMutation {
	return _c.mutation
}

// Save creates the ScriptAssignment in the database.
func (_c *ScriptAssignmentCreate) Save(ctx context.Context) (*ScriptAssignment, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ScriptAssignmentCreate) SaveX(ctx context.Context) *ScriptAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ScriptAssignmentCreate) defaults() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		v := scriptassignment.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ScriptAssignmentCreate) check() error {
	if _, ok := _c.mutation.ScriptID(); !ok {
		return &ValidationError{Name: "script_id", err: errors.New(`ent: missing required field "ScriptAssignment.script_id"`)}
	}
	if v, ok := _c.mutation.ScriptID(); ok {
		if err := scriptassignment.ScriptIDValidator(v); err != nil {
			return &ValidationError{Name: "script_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.script_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "ScriptAssignment.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := scriptassignment.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.client_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := scriptassignment.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "ScriptAssignment.id": %w`, err)}
		}
	}
	return nil
}

func (_c *ScriptAssignmentCreate) sqlSave(ctx context.Context) (*ScriptAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ScriptAssignment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ScriptAssignmentCreate) createSpec() (*ScriptAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &ScriptAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(scriptassignment.Table, sqlgraph.NewFieldSpec(scriptassignment.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(scriptassignment.FieldCreateBy, field.TypeUint32, value)
		_node.CreateBy = &value
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(scriptassignment.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = &value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(scriptassignment.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = &value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(scriptassignment.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(scriptassignment.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = &value
	}
	if value, ok := _c.mutation.ScriptID(); ok {
		_spec.SetField(scriptassignment.FieldScriptID, field.TypeString, value)
		_node.ScriptID = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(scriptassignment.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScriptAssignment.Create().
//		SetCreateBy(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScriptAssignmentUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ScriptAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *ScriptAssignmentUpsertOne {
	_c.conflict = opts
	return &ScriptAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScriptAssignmentCreate) OnConflictColumns(columns ...string) *ScriptAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScriptAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// ScriptAssignmentUpsertOne is the builder for "upsert"-ing
	//  one ScriptAssignment node.
	ScriptAssignmentUpsertOne struct {
		create *ScriptAssignmentCreate
	}

	// ScriptAssignmentUpsert is the "OnConflict" setter.
	ScriptAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreateBy sets the "create_by" field.
func (u *ScriptAssignmentUpsert) SetCreateBy(v uint32) *ScriptAssignmentUpsert {
	u.Set(scriptassignment.FieldCreateBy, v)
	return u
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptAssignmentUpsert) UpdateCreateBy() *ScriptAssignmentUpsert {
	u.SetExcluded(scriptassignment.FieldCreateBy)
	return u
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptAssignmentUpsert) AddCreateBy(v uint32) *ScriptAssignmentUpsert {
	u.Add(scriptassignment.FieldCreateBy, v)
	return u
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptAssignmentUpsert) ClearCreateBy() *ScriptAssignmentUpsert {
	u.SetNull(scriptassignment.FieldCreateBy)
	return u
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptAssignmentUpsert) SetUpdateTime(v time.Time) *ScriptAssignmentUpsert {
	u.Set(scriptassignment.FieldUpdateTime, v)
	return u
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsert) UpdateUpdateTime() *ScriptAssignmentUpsert {
	u.SetExcluded(scriptassignment.FieldUpdateTime)
	return u
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptAssignmentUpsert) ClearUpdateTime() *ScriptAssignmentUpsert {
	u.SetNull(scriptassignment.FieldUpdateTime)
	return u
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptAssignmentUpsert) SetDeleteTime(v time.Time) *ScriptAssignmentUpsert {
	u.Set(scriptassignment.FieldDeleteTime, v)
	return u
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsert) UpdateDeleteTime() *ScriptAssignmentUpsert {
	u.SetExcluded(scriptassignment.FieldDeleteTime)
	return u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptAssignmentUpsert) ClearDeleteTime() *ScriptAssignmentUpsert {
	u.SetNull(scriptassignment.FieldDeleteTime)
	return u
}

// SetScriptID sets the "script_id" field.
func (u *ScriptAssignmentUpsert) SetScriptID(v string) *ScriptAssignmentUpsert {
	u.Set(scriptassignment.FieldScriptID, v)
	return u
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsert) UpdateScriptID() *ScriptAssignmentUpsert {
	u.SetExcluded(scriptassignment.FieldScriptID)
	return u
}

// SetClientID sets the "client_id" field.
func (u *ScriptAssignmentUpsert) SetClientID(v string) *ScriptAssignmentUpsert {
	u.Set(scriptassignment.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsert) UpdateClientID() *ScriptAssignmentUpsert {
	u.SetExcluded(scriptassignment.FieldClientID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scriptassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScriptAssignmentUpsertOne) UpdateNewValues() *ScriptAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(scriptassignment.FieldID)
		}
		if _, exists := u.create.mutation.CreateTime(); exists {
			s.SetIgnore(scriptassignment.FieldCreateTime)
		}
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(scriptassignment.FieldTenantID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ScriptAssignmentUpsertOne) Ignore() *ScriptAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScriptAssignmentUpsertOne) DoNothing() *ScriptAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScriptAssignmentCreate.OnConflict
// documentation for more info.
func (u *ScriptAssignmentUpsertOne) Update(set func(*ScriptAssignmentUpsert)) *ScriptAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScriptAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ScriptAssignmentUpsertOne) SetCreateBy(v uint32) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptAssignmentUpsertOne) AddCreateBy(v uint32) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertOne) UpdateCreateBy() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptAssignmentUpsertOne) ClearCreateBy() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptAssignmentUpsertOne) SetUpdateTime(v time.Time) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertOne) UpdateUpdateTime() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptAssignmentUpsertOne) ClearUpdateTime() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptAssignmentUpsertOne) SetDeleteTime(v time.Time) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertOne) UpdateDeleteTime() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptAssignmentUpsertOne) ClearDeleteTime() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetScriptID sets the "script_id" field.
func (u *ScriptAssignmentUpsertOne) SetScriptID(v string) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetScriptID(v)
	})
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertOne) UpdateScriptID() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateScriptID()
	})
}

// SetClientID sets the "client_id" field.
func (u *ScriptAssignmentUpsertOne) SetClientID(v string) *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertOne) UpdateClientID() *ScriptAssignmentUpsertOne {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateClientID()
	})
}

// Exec executes the query.
func (u *ScriptAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScriptAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScriptAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ScriptAssignmentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ScriptAssignmentUpsertOne.ID is not supported by MySQL driver. Use ScriptAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ScriptAssignmentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ScriptAssignmentCreateBulk is the builder for creating many ScriptAssignment entities in bulk.
type ScriptAssignmentCreateBulk struct {
	config
	err      error
	builders []*ScriptAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the ScriptAssignment entities in the database.
func (_c *ScriptAssignmentCreateBulk) Save(ctx context.Context) ([]*ScriptAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ScriptAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ScriptAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ScriptAssignmentCreateBulk) SaveX(ctx context.Context) []*ScriptAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ScriptAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ScriptAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ScriptAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ScriptAssignmentUpsert) {
//			SetCreateBy(v+v).
//		}).
//		Exec(ctx)
func (_c *ScriptAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *ScriptAssignmentUpsertBulk {
	_c.conflict = opts
	return &ScriptAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ScriptAssignmentCreateBulk) OnConflictColumns(columns ...string) *ScriptAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ScriptAssignmentUpsertBulk{
		create: _c,
	}
}

// ScriptAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of ScriptAssignment nodes.
type ScriptAssignmentUpsertBulk struct {
	create *ScriptAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(scriptassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ScriptAssignmentUpsertBulk) UpdateNewValues() *ScriptAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(scriptassignment.FieldID)
			}
			if _, exists := b.mutation.CreateTime(); exists {
				s.SetIgnore(scriptassignment.FieldCreateTime)
			}
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(scriptassignment.FieldTenantID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ScriptAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ScriptAssignmentUpsertBulk) Ignore() *ScriptAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ScriptAssignmentUpsertBulk) DoNothing() *ScriptAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ScriptAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *ScriptAssignmentUpsertBulk) Update(set func(*ScriptAssignmentUpsert)) *ScriptAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ScriptAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreateBy sets the "create_by" field.
func (u *ScriptAssignmentUpsertBulk) SetCreateBy(v uint32) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetCreateBy(v)
	})
}

// AddCreateBy adds v to the "create_by" field.
func (u *ScriptAssignmentUpsertBulk) AddCreateBy(v uint32) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.AddCreateBy(v)
	})
}

// UpdateCreateBy sets the "create_by" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertBulk) UpdateCreateBy() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateCreateBy()
	})
}

// ClearCreateBy clears the value of the "create_by" field.
func (u *ScriptAssignmentUpsertBulk) ClearCreateBy() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearCreateBy()
	})
}

// SetUpdateTime sets the "update_time" field.
func (u *ScriptAssignmentUpsertBulk) SetUpdateTime(v time.Time) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetUpdateTime(v)
	})
}

// UpdateUpdateTime sets the "update_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertBulk) UpdateUpdateTime() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateUpdateTime()
	})
}

// ClearUpdateTime clears the value of the "update_time" field.
func (u *ScriptAssignmentUpsertBulk) ClearUpdateTime() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearUpdateTime()
	})
}

// SetDeleteTime sets the "delete_time" field.
func (u *ScriptAssignmentUpsertBulk) SetDeleteTime(v time.Time) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetDeleteTime(v)
	})
}

// UpdateDeleteTime sets the "delete_time" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertBulk) UpdateDeleteTime() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateDeleteTime()
	})
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (u *ScriptAssignmentUpsertBulk) ClearDeleteTime() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.ClearDeleteTime()
	})
}

// SetScriptID sets the "script_id" field.
func (u *ScriptAssignmentUpsertBulk) SetScriptID(v string) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetScriptID(v)
	})
}

// UpdateScriptID sets the "script_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertBulk) UpdateScriptID() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateScriptID()
	})
}

// SetClientID sets the "client_id" field.
func (u *ScriptAssignmentUpsertBulk) SetClientID(v string) *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *ScriptAssignmentUpsertBulk) UpdateClientID() *ScriptAssignmentUpsertBulk {
	return u.Update(func(s *ScriptAssignmentUpsert) {
		s.UpdateClientID()
	})
}

// Exec executes the query.
func (u *ScriptAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ScriptAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ScriptAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ScriptAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
