// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Action is the predicate function for action builders.
type Action func(*sql.Selector)

// ActionFile is the predicate function for actionfile builders.
type ActionFile func(*sql.Selector)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// ExecutionLog is the predicate function for executionlog builders.
type ExecutionLog func(*sql.Selector)

// Script is the predicate function for script builders.
type Script func(*sql.Selector)

// ScriptAssignment is the predicate function for scriptassignment builders.
type ScriptAssignment func(*sql.Selector)

// Workflow is the predicate function for workflow builders.
type Workflow func(*sql.Selector)
