// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuditLog is the predicate function for auditlog builders.
type AuditLog func(*sql.Selector)

// ExecutionLog is the predicate function for executionlog builders.
type ExecutionLog func(*sql.Selector)

// Script is the predicate function for script builders.
type Script func(*sql.Selector)

// ScriptAssignment is the predicate function for scriptassignment builders.
type ScriptAssignment func(*sql.Selector)
