// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ExecutorAuditLogsColumns holds the columns for the "executor_audit_logs" table.
	ExecutorAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "audit_id", Type: field.TypeString, Unique: true, Comment: "Unique audit log identifier (UUID)"},
		{Name: "request_id", Type: field.TypeString, Nullable: true, Comment: "Request ID from metadata"},
		{Name: "operation", Type: field.TypeString, Comment: "gRPC operation path"},
		{Name: "service_name", Type: field.TypeString, Comment: "Service name", Default: "executor-service"},
		{Name: "client_id", Type: field.TypeString, Nullable: true, Comment: "Client ID from certificate CN"},
		{Name: "client_common_name", Type: field.TypeString, Nullable: true, Comment: "Client certificate common name"},
		{Name: "client_organization", Type: field.TypeString, Nullable: true, Comment: "Client certificate organization"},
		{Name: "client_serial_number", Type: field.TypeString, Nullable: true, Comment: "Client certificate serial number"},
		{Name: "is_authenticated", Type: field.TypeBool, Comment: "Whether the client was authenticated via mTLS", Default: false},
		{Name: "success", Type: field.TypeBool, Comment: "Whether the operation succeeded", Default: true},
		{Name: "error_code", Type: field.TypeInt32, Nullable: true, Comment: "Error code if failed"},
		{Name: "error_message", Type: field.TypeString, Nullable: true, Comment: "Error message if failed"},
		{Name: "latency_ms", Type: field.TypeInt64, Comment: "Operation latency in milliseconds", Default: 0},
		{Name: "peer_address", Type: field.TypeString, Nullable: true, Comment: "Client IP address"},
		{Name: "geo_location", Type: field.TypeJSON, Nullable: true, Comment: "Geographic location info"},
		{Name: "log_hash", Type: field.TypeString, Nullable: true, Comment: "SHA-256 hash of the log content"},
		{Name: "signature", Type: field.TypeBytes, Nullable: true, Comment: "ECDSA signature for integrity verification"},
		{Name: "metadata", Type: field.TypeJSON, Nullable: true, Comment: "Additional metadata"},
	}
	// ExecutorAuditLogsTable holds the schema information for the "executor_audit_logs" table.
	ExecutorAuditLogsTable = &schema.Table{
		Name:       "executor_audit_logs",
		Columns:    ExecutorAuditLogsColumns,
		PrimaryKey: []*schema.Column{ExecutorAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "executor_auditlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[4]},
			},
			{
				Name:    "executor_auditlog_tenant_client",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[4], ExecutorAuditLogsColumns[9]},
			},
			{
				Name:    "executor_auditlog_tenant_operation",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[4], ExecutorAuditLogsColumns[7]},
			},
			{
				Name:    "executor_auditlog_tenant_success",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[4], ExecutorAuditLogsColumns[14]},
			},
			{
				Name:    "executor_auditlog_operation",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[7]},
			},
			{
				Name:    "executor_auditlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[9]},
			},
			{
				Name:    "executor_auditlog_success",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[14]},
			},
			{
				Name:    "executor_auditlog_peer_address",
				Unique:  false,
				Columns: []*schema.Column{ExecutorAuditLogsColumns[18]},
			},
		},
	}
	// ExecutorExecutionLogsColumns holds the columns for the "executor_execution_logs" table.
	ExecutorExecutionLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "script_id", Type: field.TypeString, Size: 36, Comment: "FK to executor_scripts"},
		{Name: "script_name", Type: field.TypeString, Size: 255, Comment: "Denormalized script name for audit readability"},
		{Name: "client_id", Type: field.TypeString, Size: 255, Comment: "mTLS client CN"},
		{Name: "script_hash", Type: field.TypeString, Size: 64, Comment: "Script content hash at execution time"},
		{Name: "trigger_type", Type: field.TypeEnum, Comment: "Who initiated the execution", Enums: []string{"CLIENT_PULL", "UI_PUSH"}},
		{Name: "status", Type: field.TypeEnum, Comment: "Current execution status", Enums: []string{"PENDING", "RUNNING", "COMPLETED", "FAILED", "REJECTED_HASH_MISMATCH", "REJECTED_NOT_APPROVED", "CLIENT_OFFLINE"}, Default: "PENDING"},
		{Name: "exit_code", Type: field.TypeInt, Nullable: true, Comment: "Process exit code"},
		{Name: "output", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Script stdout"},
		{Name: "error_output", Type: field.TypeString, Nullable: true, Size: 2147483647, Comment: "Script stderr"},
		{Name: "rejection_reason", Type: field.TypeString, Nullable: true, Size: 1024, Comment: "Why the client rejected execution"},
		{Name: "started_at", Type: field.TypeTime, Nullable: true, Comment: "When execution started on client"},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true, Comment: "When execution completed on client"},
		{Name: "duration_ms", Type: field.TypeInt64, Nullable: true, Comment: "Execution duration in milliseconds"},
	}
	// ExecutorExecutionLogsTable holds the schema information for the "executor_execution_logs" table.
	ExecutorExecutionLogsTable = &schema.Table{
		Name:       "executor_execution_logs",
		Columns:    ExecutorExecutionLogsColumns,
		PrimaryKey: []*schema.Column{ExecutorExecutionLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "executionlog_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[5]},
			},
			{
				Name:    "executionlog_script_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[6]},
			},
			{
				Name:    "executionlog_client_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[8]},
			},
			{
				Name:    "executionlog_status",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[11]},
			},
			{
				Name:    "executionlog_tenant_id_script_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[5], ExecutorExecutionLogsColumns[6]},
			},
			{
				Name:    "executionlog_tenant_id_client_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[5], ExecutorExecutionLogsColumns[8]},
			},
			{
				Name:    "executionlog_tenant_id_status",
				Unique:  false,
				Columns: []*schema.Column{ExecutorExecutionLogsColumns[5], ExecutorExecutionLogsColumns[11]},
			},
		},
	}
	// ExecutorScriptsColumns holds the columns for the "executor_scripts" table.
	ExecutorScriptsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "update_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "name", Type: field.TypeString, Size: 255, Comment: "Script name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 2048, Comment: "Script description"},
		{Name: "script_type", Type: field.TypeEnum, Comment: "Script execution engine type", Enums: []string{"BASH", "JAVASCRIPT", "LUA"}},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Comment: "Script body content"},
		{Name: "content_hash", Type: field.TypeString, Size: 64, Comment: "SHA256 hex digest of content"},
		{Name: "version", Type: field.TypeInt, Comment: "Content version, incremented on update", Default: 1},
		{Name: "enabled", Type: field.TypeBool, Comment: "Whether the script is active", Default: true},
	}
	// ExecutorScriptsTable holds the schema information for the "executor_scripts" table.
	ExecutorScriptsTable = &schema.Table{
		Name:       "executor_scripts",
		Columns:    ExecutorScriptsColumns,
		PrimaryKey: []*schema.Column{ExecutorScriptsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "script_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptsColumns[6]},
			},
			{
				Name:    "script_tenant_id_name",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptsColumns[6], ExecutorScriptsColumns[7]},
			},
			{
				Name:    "script_tenant_id_script_type",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptsColumns[6], ExecutorScriptsColumns[9]},
			},
			{
				Name:    "script_tenant_id_enabled",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptsColumns[6], ExecutorScriptsColumns[13]},
			},
		},
	}
	// ExecutorScriptAssignmentsColumns holds the columns for the "executor_script_assignments" table.
	ExecutorScriptAssignmentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString, Unique: true, Comment: "UUID primary key"},
		{Name: "create_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "create_time", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "update_time", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "delete_time", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "script_id", Type: field.TypeString, Size: 36, Comment: "FK to executor_scripts"},
		{Name: "client_id", Type: field.TypeString, Size: 255, Comment: "mTLS client CN"},
	}
	// ExecutorScriptAssignmentsTable holds the schema information for the "executor_script_assignments" table.
	ExecutorScriptAssignmentsTable = &schema.Table{
		Name:       "executor_script_assignments",
		Columns:    ExecutorScriptAssignmentsColumns,
		PrimaryKey: []*schema.Column{ExecutorScriptAssignmentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "executor_assignment_unique",
				Unique:  true,
				Columns: []*schema.Column{ExecutorScriptAssignmentsColumns[6], ExecutorScriptAssignmentsColumns[7], ExecutorScriptAssignmentsColumns[5]},
			},
			{
				Name:    "scriptassignment_script_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptAssignmentsColumns[6]},
			},
			{
				Name:    "scriptassignment_client_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptAssignmentsColumns[7]},
			},
			{
				Name:    "scriptassignment_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{ExecutorScriptAssignmentsColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ExecutorAuditLogsTable,
		ExecutorExecutionLogsTable,
		ExecutorScriptsTable,
		ExecutorScriptAssignmentsTable,
	}
)

func init() {
	ExecutorAuditLogsTable.Annotation = &entsql.Annotation{
		Table: "executor_audit_logs",
	}
	ExecutorExecutionLogsTable.Annotation = &entsql.Annotation{
		Table: "executor_execution_logs",
	}
	ExecutorScriptsTable.Annotation = &entsql.Annotation{
		Table: "executor_scripts",
	}
	ExecutorScriptAssignmentsTable.Annotation = &entsql.Annotation{
		Table: "executor_script_assignments",
	}
}
