// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-executor/internal/cert"
	"github.com/go-tangra/go-tangra-executor/internal/data"
	"github.com/go-tangra/go-tangra-executor/internal/server"
	"github.com/go-tangra/go-tangra-executor/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	certManager, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	scriptRepo := data.NewScriptRepo(context, entClient)
	assignmentRepo := data.NewAssignmentRepo(context, entClient)
	portalClient, cleanup2, err := data.NewPortalClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	scriptService := service.NewScriptService(context, scriptRepo, assignmentRepo, portalClient)
	assignmentService := service.NewAssignmentService(context, assignmentRepo, scriptRepo)
	executionLogRepo := data.NewExecutionLogRepo(context, entClient)
	commandRegistry := service.NewCommandRegistry()
	executionService := service.NewExecutionService(context, scriptRepo, assignmentRepo, executionLogRepo, commandRegistry)
	clientService := service.NewClientService(context, scriptRepo, assignmentRepo, executionLogRepo, commandRegistry)
	grpcServer := server.NewGRPCServer(context, certManager, scriptService, assignmentService, executionService, clientService)
	app := newApp(context, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
